- ci/release/_install.sh
- install.sh
@ejulio-ts missed that he had to do something after install, and I think it won't be uncommon for others to as well. This adds a little callout that should catch the majority of cases.
Also adds a link to report issue if something went wrong
> install: add callout to next steps in terminal display

- ci/release/changelogs/next.md
- d2renderers/d2svg/github-markdown.css
- e2etests/testdata/stable/chaos2/dagre/sketch.exp.svg
- e2etests/testdata/stable/chaos2/elk/sketch.exp.svg
- e2etests/testdata/stable/giant_markdown_test/dagre/sketch.exp.svg
- e2etests/testdata/stable/giant_markdown_test/elk/sketch.exp.svg
- e2etests/testdata/stable/hr/dagre/sketch.exp.svg
- e2etests/testdata/stable/hr/elk/sketch.exp.svg
- e2etests/testdata/stable/li1/dagre/sketch.exp.svg
- e2etests/testdata/stable/li1/elk/sketch.exp.svg
- e2etests/testdata/stable/li2/dagre/sketch.exp.svg
- e2etests/testdata/stable/li2/elk/sketch.exp.svg
- e2etests/testdata/stable/li3/dagre/sketch.exp.svg
- e2etests/testdata/stable/li3/elk/sketch.exp.svg
- e2etests/testdata/stable/li4/dagre/sketch.exp.svg
- e2etests/testdata/stable/li4/elk/sketch.exp.svg
- e2etests/testdata/stable/lone_h1/dagre/sketch.exp.svg
- e2etests/testdata/stable/lone_h1/elk/sketch.exp.svg
- e2etests/testdata/stable/markdown/dagre/sketch.exp.svg
- e2etests/testdata/stable/markdown/elk/sketch.exp.svg
- e2etests/testdata/stable/md_code_block_fenced/dagre/sketch.exp.svg
- e2etests/testdata/stable/md_code_block_fenced/elk/sketch.exp.svg
- e2etests/testdata/stable/md_code_block_indented/dagre/sketch.exp.svg
- e2etests/testdata/stable/md_code_block_indented/elk/sketch.exp.svg
- e2etests/testdata/stable/md_code_inline/dagre/sketch.exp.svg
- e2etests/testdata/stable/md_code_inline/elk/sketch.exp.svg
- e2etests/testdata/stable/p/dagre/sketch.exp.svg
- e2etests/testdata/stable/p/elk/sketch.exp.svg
- e2etests/testdata/stable/pre/dagre/sketch.exp.svg
- e2etests/testdata/stable/pre/elk/sketch.exp.svg
Previously markdown styling would change with the system light/dark mode setting, but we don't want this behavior.
- always render with light mode styles
- Fixes #159
> render: consistent md render regardless of system dark mode

- cmd/d2/main.go
- d2layouts/d2sequence/constants.go
- d2layouts/d2sequence/layout.go
- d2layouts/d2sequence/layout_test.go
Adds `d2sequence` layout for sequence diagrams with basic functionality.
The layout is behind a flag for now as it will need changes in `D2` for full support. So, to merge these changes in small PRs, lets have it behind a flag that also allows us to test it locally without much friction.
Assumptions:
- edges are kept in order as they are defined
- object order is identified as they appear in edge order
- the lifeline edge follows the shape stroke style, except for `stroke-dash` that is constant
No changelog as this is not ready yet. Will add the line once we got it properly integrated.
here is an example diagram
```
alice: "Alice\nline\nbreaker" {
shape: person
style.stroke: red
}
bob: "Bob" {
shape: person
style.stroke-width: 5
}
db: {
shape: cylinder
}
queue: {
shape: queue
}
service: …
```
> Adds basic sequence diagrams behind a layout flag

- d2compiler/compile.go
- d2compiler/compile_test.go
- d2target/d2target.go
- testdata/d2compiler/TestCompile/basic_sequence.exp.json
- testdata/d2compiler/TestCompile/root_sequence.exp.json
This enables running sequence layout engine only on sequence shapes.
Supports #99
> syntax: shape: sequence

- d2layouts/d2sequence/layout.go
- d2layouts/d2sequence/layout_test.go
Supports #99 
Set index for spans to 1 so that they are rendered after everything else
> Fix span render

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- cmd/d2/help.go
- cmd/d2/main.go
- cmd/d2/static/watch.css
- cmd/d2/static/watch.js
- cmd/d2/watch.go
- go.mod
- lib/imgbundler/imgbundler.go
- lib/imgbundler/imgbundler_test.go
- lib/xmain/opts.go
See individual commits.
And please test @alixander
> imgbundler and CLI fixes

- lib/version/version.go
More clear. See https://github.com/terrastruct/d2/issues/202
> lib/version: Set to HEAD when building from source instead of ????

- ci/release/changelogs/next.md
- watch.go
Will prevent the benign watching errors we've been seeing.
I feel like there was an open issue for this but I cannot find it.
> watch.go: Ignore first error in ensureAddWatch

- .gitignore
- autofmt.go
- ci/dev.sh
- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- fmt.go
- help.go
- lib/xmain/xmain.go
- main.go
- ci/dev.sh: Add
- lib/xmain: Print usage info in separate log
- d2format: Expose in CLI under fmt subcommand
> d2format: Expose in CLI under fmt subcommand

- Makefile
- README.md
- ci/fmt.sh
See https://github.com/terrastruct/ci/blob/a875763eccbb51298807901be68c31e5b150dceb/lib/misc.sh#L28
The TOC is generated via pandoc and inserted via shell. ``
marks the insertion point, the TOC is inserted right below.
I'm using this in utils-go too. We should use it anywhere else we need
TOCs. I'm sure pandoc can handle the frontmatter in d2-docs too.
> Add markdown TOC generation using pandoc and shell

- d2layouts/d2dagrelayout/dagre.js
- d2layouts/d2dagrelayout/layout.go
- d2plugin/plugin_dagre.go
- go.mod
- go.sum
> switch dagre to Goja

- ci/release/_build.sh
- ci/release/_install.sh
- ci/release/build.sh
- ci/release/builders/aws_ensure.sh
- ci/release/changelogs/next.md
- ci/release/gen_install.sh
- ci/release/gen_template_lib.sh
- ci/release/template/Makefile
- ci/release/template/README.md.sh
- ci/release/template/scripts/install.sh
- ci/release/template/scripts/lib.sh
- ci/release/template/scripts/uninstall.sh
- d2chaos/d2chaos.go
- docs/INSTALL.md
- install.sh
As before we default to /usr/local but now we switch to ~/.local if /usr/local if not accessible instead of prompting for sudo. Instead of having an exception for macOS/arm64.
Of course if a user wants to install in /usr/local anyway, they can still pass --prefix /usr/local to force installation into /usr/local and prompt for sudo.
> install.sh: Improve default $PREFIX behaviour

- ci/release/changelogs/next.md
Changelogs can't be hard wrapped. Markdown text in bullets isn't
automatically soft wrapped on render like paragraphs.
> changelogs/next.md: Fix wrapping

- d2target/d2target.go
- e2etests/testdata/sanity/empty/dagre/sketch.exp.svg
- e2etests/testdata/sanity/empty/elk/sketch.exp.svg
found through https://github.com/terrastruct/d2/actions/runs/3635230859/jobs/6134140375 
shouldn't be setting empty diagram viewbox to ridiculous number
> fix empty diagram

- lib/urlenc/urlenc.go
adding keys from maps results in non-deterministic compression dict
> fix urlencode compression determinism

- ci/release/changelogs/next.md
- d2graph/serde.go
- d2graph/serde_test.go
binary plugins were getting a corrupted graph due to serde bug where object children were being set case sensitive
> fix serialization casing

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2renderers/d2svg/d2svg.go
- docs/examples/lib/1-d2lib/d2lib.go
- docs/examples/lib/3-lowlevel/lowlevel.go
- e2etests/e2e_test.go
- main.go
- watch.go
i've been sneakily adjusting padding for myself to generate d2lang.com images. time to make this generally available.
Default padding vs `--pad=0`:
closes #14
> cli: add pad option

- ci/release/changelogs/next.md
- d2format/format.go
- d2format/format_test.go
> fmt: Preserve leading comment spacing

- README.md
- ci/release/changelogs/next.md
> release notes msg

- ci/release/changelogs/next.md
- fmt.go
fixes #469 
match behavior of gofmt: https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt.go#L266
tested the original issue's command and confirmed it only writes once as expected
> only write fmt if changed

- ci/e2ereport.sh
- e2etests/e2e_test.go
Fixes .got.svg files being deleted for changed tests when running ./ci/e2ereport.sh with -delta flag. These are needed to produce the report.
- when running the report, only delete the `.got.svg` files if there were no changes
- separated change out from #447
> fix e2ereport script with delta flag

- d2layouts/d2dagrelayout/dagre.js
- docs/examples/lib/README.md
This PR fixes typos in two files (`README.md`, `dagre.js`.
It also converts some links from `http` to `https`.
> doc: fixing typos

- ci/release/changelogs/next.md
- static/watch.js
Closes #540
Set the width/height of the svg to fit the current screen width/height to make it fit the screen.
> watch: set width/height of svg to fit screen

- ci/release/template/man/d2.1
- cmd/d2plugin-dagre/main.go
- d2chaos/d2chaos_test.go
- d2exporter/export_test.go
- d2layouts/d2dagrelayout/layout.go
- d2layouts/d2elklayout/layout.go
- d2lib/c.go
- d2lib/d2.go
- d2plugin/exec.go
- d2plugin/plugin.go
- d2plugin/plugin_dagre.go
- d2plugin/plugin_elk.go
- d2plugin/serve.go
- d2renderers/d2sketch/sketch_test.go
- d2renderers/d2svg/appendix/appendix_test.go
- docs/examples/lib/1-d2lib/d2lib.go
- docs/examples/lib/2-d2oracle/d2oracle.go
- docs/examples/lib/3-lowlevel/lowlevel.go
- e2etests/e2e_test.go
- help.go
- main.go
Layout configs do not pollute the main flagset. They are hidden. They are shown when the command for layout help is run:
> Pass layout configs

- docs/CONTRIBUTING.md
> add go version to contributing.md

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/dimension_with_style.exp.json
> fix dimension with style

- README.md
I have added a reference link to a Community plugins to build JavaScript D2 diagram in D2
> docs: Adding JS D2 diagram builder to README.md

- ci/release/Dockerfile
- ci/release/linux/Dockerfile
fixed: https://github.com/terrastruct/d2/issues/594
```
err: failed to install Playwright: could not install driver: could not install driver: could not download driver: Get "https://playwright.azureedge.net/builds/driver/next/playwright-1.20.0-beta-1647057403000-linux.zip": x509: certificate signed by unknown authority
```
> docker: add ca-certificates package

- ci/e2ereport.sh
Continuation from unverified/unsigned commits on #690
> Add test to see if command exists with POSIX 'command'

- e2etests/report/main.go
- e2etests/report/template.html
If the `REPORT_OUTPUT` env var is used, the links to svgs in the e2ereport would not be correct.
This fixes the broken report links by ensuring they are set to be relative to the report even if it is not in the default file location.
- store abs paths in TestItem
- get abs path of report directory
- compute relative path of test svg (relative to report) and use that in the report
- fixed `Got` label position when not running `-delta` flag
> fix e2ereport to ensure test paths are relative to report

- d2renderers/d2svg/d2svg.go
- lib/shape/shape.go
- lib/shape/shape_callout.go
- lib/shape/shape_circle.go
- lib/shape/shape_class.go
- lib/shape/shape_cloud.go
- lib/shape/shape_code.go
- lib/shape/shape_cylinder.go
- lib/shape/shape_diamond.go
- lib/shape/shape_document.go
- lib/shape/shape_hexagon.go
- lib/shape/shape_image.go
- lib/shape/shape_oval.go
- lib/shape/shape_package.go
- lib/shape/shape_page.go
- lib/shape/shape_parallelogram.go
- lib/shape/shape_person.go
- lib/shape/shape_queue.go
- lib/shape/shape_real_square.go
- lib/shape/shape_square.go
- lib/shape/shape_step.go
- lib/shape/shape_stored_data.go
- lib/shape/shape_table.go
- lib/shape/shape_text.go
Update `GetInsidePlacement` to use shape specific inner boxes and per-axis padding.
- fix `GetInsidePlacement` not using the shape specific innerBoxes
- fix oval's `GetInsidePlacement` positioning with all the padding on the left/top sides (instead of half on each side)
- update arguments to take in padding for each axis
- function not used in dagre/elk layouts so no test changes
> fix shape get inside placement

- d2chaos/d2chaos.go
d2 chaos but with less chaos in IDs and labels so it is much easier to see what the problem is when there is a failure.
- related #752 
```
--- FAIL: TestD2Chaos/#00 (0.00s)
d2chaos_test.go:82: failed to create "\"cP\\n\x19*U<Sx\bH#\x05gE\x06u\".\"+hxZyS\x11hZT)wv\\$\x18\x11;N!i-sI4\v^)\x1f\" -> \"cP\\n\x19*U<Sx\bH#\x05gE\x06u\".\"+hxZyS\x11hZT)wv\\$\x18\x11;N!i-sI4\v^)\x1f\".\"\"": failed to recompile:
"cP\n*U<SH#gEu": {
"+hxZyShZT)wv\$;N!i-sI4
^)": {
shape: cloud
v: {shape: circle}
"": {
shape: sequence_diagram
p]      5:-Qw[(S=Te-<Di hsJ0'8Tl3tMH/4nQ[Z]W": '"YG\$pCd0jS;42
h7]ZO]  nL*\$Jrw       PZ0&c9%  f61>\n|d:G%n)\n#7|@WfUzR^Zk&SG
<z\n73Cg"' {shape: rectangle}X\n8E;A4
}
}
"N]": {shape: package}
"+hxZyShZT)wv\$;N!i-sI4
^)" -> "+hxZyShZT)wv\$;N!i-sI4
^)".""
}
"cP\n*U<SH#gEu" -- …
```
> testing chaos with more readable/simpler ids and labels

- Makefile
- docs/examples/twitter/in.d2
updating for style keyword changes from #714
> update example d2 file

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/d2ir.go
- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2compiler/TestCompile/underscore_connection.exp.json
- testdata/d2oracle/TestMove/underscore-connection.exp.json
1. edge case where creating a new edge with underscores AND common prefix was panicking
2. moving an object where the most nested reference is an edge
> fix 2 bugs: compiler: underscores in edges; oracle: edge ref

- ci/release/changelogs/next.md
- main.go
- watch.go
Instead we log the duration each layer's full compilation took.
> watch: Fix duplicate logs and remove timestamps

- d2plugin/exec.go
- d2plugin/plugin.go
- d2plugin/plugin_dagre.go
- d2plugin/plugin_elk.go
A plugin from FindPlugin will now return the correct Type and Path when
calling info on it. Before, they would only be set on ListPluginInfos
which makes no sense.
> d2plugin: Have each plugin return the correct Type

- ci/release/changelogs/next.md
- d2graph/serde.go
- d2graph/serde_test.go
when rendering the following diagram with `TALA`, it errored when adding `no collision.near: game loop.collision detected`
```
direction: down
first input -> start game -> game loop
game loop: {
direction: down
input -> increase bird top velocity
move bird -> move pipes -> render
render -> no collision -> wait 16 milliseconds -> move bird
render -> collision detected -> game over
no collision.near: game loop.collision detected
}
```
The reason was that when deserializing the graph, `game loop.Children` had the full path `game loop.collision detection` instead of just `collision detection`. Then, TALA failed to find the `near` object and resulted in a `panic`.
> serde: fiz deserialize

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- d2oracle/edit_test.go
- testdata/d2compiler/TestCompile/near-invalid.exp.json
- testdata/d2oracle/TestMove/invalid-near.exp.json
- testdata/d2oracle/TestMove/near.exp.json
near key cannot be set to direct ancestor or descendant. it makes no sense.
Thanks to https://discord.com/channels/976899413542830181/1019365046486306957/1076895091379154977
> validate near key better

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestSet/edge_merge_arrowhead.exp.json
- testdata/d2oracle/TestSet/replace_edge_style.exp.json
- testdata/d2oracle/TestSet/replace_edge_style_map.exp.json
fixes up previous PRs on arrowhead handling, but also fixes existing bug where setting `stroke-dash` in this d2 script would add another line instead of replacing.
```
x -> y: {
style: {
stroke-dash: 3
}
}
```
> fix edge keying

- d2ast/d2ast.go
- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestSet/edge_flat_merge_arrowhead.exp.json
- testdata/d2oracle/TestSet/edge_index_merge_style.exp.json
Previously if you had
```
x -> y -> z
(x -> y)[0].style.opacity: 0.4
```
and then set style.opacity, it would keep appending new lines instead of replacing the value.
> fix edge key index value

- ci/release/aws/ensure.sh
- ci/release/build.sh
- ci/release/changelogs/next.md
- ci/release/docker/Dockerfile
- lib/png/png.go
- docker: Install playwright dependencies on arm64
- docker: Build images cross platform natively
> Add playwright deps to arm64 docker image

- ci/release/changelogs/next.md
- d2cli/main.go
- d2renderers/d2svg/d2svg.go
Disabling fit to screen behavior with png export so it is rendered at the correct size. Related #721.
- set dimensions on wrapper svg to disable fit screen behavior
- disable fit screen when exporting to PNG
> Fix png export

- d2cli/main.go
- d2themes/d2themes.go
- lib/pdf/pdf.go
Needed to be able to parse theme colors like "N7" when filling the background of PDF exports.
> pdf: Fix pdf fill when using theme colors

- d2renderers/d2svg/appendix/appendix.go
Fixes a regression where the background rect of the svg wouldn't be resized according to the appendix.
This could cause png renders with an appendix to not have the background set properly.
- missed this change in #725
- fixes regression of https://github.com/terrastruct/d2/pull/613#issuecomment-1407083640
> render: update background rect width and height for appendix

- ci/release/changelogs/next.md
- d2cli/static/watch.css
- d2cli/static/watch.js
Fixes zoom not working in watch mode.
- fixes #943 
- the svg in html would previously always be fit to the window size making zoomming ineffective
- use old resizing js in watch mode with the inner SVG
https://user-images.githubusercontent.com/85081687/222015338-747ef386-5e99-4052-9433-94fdf9d171b7.mp4
https://user-images.githubusercontent.com/85081687/222015343-8a539e98-b2b2-4987-915f-0927ba43a995.mp4
> fix zoom in watch mode

- ci/release/changelogs/next.md
- d2oracle/edit.go
- d2oracle/edit_test.go
also adds an assertion to all IDDelta tests to ensure that deltas never give back two IDs that equal each other.
> d2oracle: fix conflicting id's to parent

- d2oracle/edit.go
- d2oracle/edit_test.go
follow up to https://github.com/terrastruct/d2/pull/957
another edge case. when generating new IDs in batch, like deleting a container and having to hoist children up, we have to make sure that the *generated* IDs don't conflict with each other as well.
> d2oracle: fix generated ids in deltas

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestDelete/conflicts_generated.exp.json
deleting a container hoists its children up, giving them unique IDs
there was a bug where these IDs overwrote each other.
> fix delete container hoisting children

- make.sh
This code:
1. Extracts the required go minor from `go.mod`
2. Gets the current go version from `go version` and normalizes it
3. Checks whether the required go minor is a version prefix for the current go
version, and bails if it isn't.
The conditional is more complicated than it would be if this script supported bash extensions to the POSIX shell standard, but changing to `#!/bin/bash` seemed out of scope for this change.
> build: `make` bails on the wrong go version

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/compile.go
- d2ir/d2ir.go
- testdata/d2compiler/TestCompile/image_children.exp.json
- testdata/d2compiler/TestCompile/image_children_Steps.exp.json
there was an issue where a user defined `Steps` as a child of image shape, and we were treating it case sensitive in some places and case insensitive in others. 
this change makes d2ir compile the fields to lowercase if it's reserved
> case insensitive reserved keyword matching

- ci/release/changelogs/next.md
- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestSet/replace_fill_pattern.exp.json
- testdata/d2oracle/TestSet/set_fill_pattern.exp.json
Fill-pattern wasn't getting replaced correctly when called via `set`
> d2Oracle: Fix fill-pattern replacement in d2Oracle

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/near_near_const.exp.json
Fixes an issue where a near could be set to a title object.
- title objects (with a constant near value) are separate from everything else so there shouldn't be a near to them
- adds compiler test for this scenario
> add compiler error for near set to title with constant near

- ci/release/changelogs/next.md
- d2cli/static/watch.js
Fixes a bug where the svg structure could become corrupted in watch mode due to a self-closing div.
- fixes #1084 
- when setting innerHTML in watchmode, it would parse a self-closing div incorrectly
- Issue seems to be from self closing div tags being invalid in html.  https://stackoverflow.com/a/206409
- Note: in windows, a md label block is considered not an empty label, containing a `\r` char.  However this can also happen without CRLF endings a md block with 2 newlines :  
```d2
you: {shape: person}
you -> form
form: {
get: |md
|
}
```
self closing div ends up parsed as an open div tag
> fix watch mode parsing of self-closing div in svg

- ci/release/changelogs/next.md
- lib/font/font.go
If you put the uint32 type at the top instead of later, 32 bit builds
All credit @ahesford
> fix builds on 32bit

- README.md
The author's GitHub account has been suspended due to sanctions. I replaced it with a link to the original repository, where he keeps working.
> update link to tree-sitter grammar

- lib/png/generate_png.js
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas, canvas has a max 32,767 for each dimension and a total area max of 268,435,456 pixels. 
Here is a generated png of the problematic d2 code before:
[demo.png.zip](https://github.com/terrastruct/d2/files/11226460/demo.png.zip)
I can't even upload the actual png because the file side is too big
Closes https://github.com/terrastruct/d2/issues/1093
closes #964
> exports: Prevent exports over canvas max dimensions

- d2graph/d2graph.go
- d2graph/serde.go
- d2layouts/d2dagrelayout/layout.go
- d2layouts/d2elklayout/layout.go
- d2layouts/d2near/layout.go
- d2layouts/d2sequence/sequence_diagram.go
Refactors `d2graph.Object` to remove redundant fields `LabelWidth` and `LabelHeight` and use `LabelDimensions`.
- consistency with `d2graph.Edge` `LabelDimensions`
- replace long-range nil check assumptions with `HasLabel()`
> refactor LabelWidth and LabelHeight to LabelDimensions

- .github/workflows/ci.yml
- .github/workflows/daily.yml
- .github/workflows/project.yml
- ci/release/changelogs/v0.1.0.md
- ci/release/changelogs/v0.1.5.md
- ci/release/changelogs/v0.3.0.md
- d2compiler/compile.go
- d2graph/serde.go
- d2layouts/d2layoutfeatures/d2layoutfeatures.go
- d2plugin/plugin_features.go
- d2renderers/d2fonts/README.md
- d2themes/sketch_overlay.go
- lib/geo/segment_test.go
- lib/pdf/pdf.go
The [go report card](https://goreportcard.com/report/oss.terrastruct.com/d2) for this project complains about misspellings in this project. This PR corrects this and fixes a few other typos on the way.
> chore: fixing typos

- ci/release/changelogs/next.md
- d2plugin/serve.go
- e2etests-cli/main_test.go
accidental/invalid arg construction could lead to a panic with flags being parsed multiple times
closes #738
> fix reparsing flags

- lib/geo/point.go
- lib/geo/route.go
Update GetPointAtDistance to work with distances greater than route length.
- previously this would work with negative distances but not distances greater than route length
- continues from the first/last segment when distance is out of range
> update get point at distance

- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/tail-style-map.exp.json
- testdata/d2compiler/TestCompile/tail-style.exp.json
D2 shouldn't consider an empty map for `style` valid.
There's an edge case where you 
1. parse, have no errors
2. format, removes empty maps
3. compile, error due to `style` being standalone (the assumption is that by step 3, there are no more errors because the caller has already validated with `parse`, and `format` should never change that outcome).
> fix `style` validation

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestMove/include_descendants_underscore_2.exp.json
- testdata/d2oracle/TestMove/include_descendants_underscore_3.exp.json
covers the case where the ref being moved is a map with children nodes that have underscores
> d2oracle: fix underscores for move with descendant

- ci/release/changelogs/next.md
- d2cli/main.go
- e2etests-cli/main_test.go
- e2etests-cli/testdata/TestCLI_E2E/empty-base.exp.svg
closes #1353
the issue wasn't that it needed to be skipped. It had a `direction: down` so it wasn't considered empty.
The issue is that when you get rid of that `direction: down` to make it truly empty, the CLI didn't produce anything at all. We were skipping renders of folders in animations.
> fix empty base for animations

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/nested-array-classes.exp.json
> fix multiple classes modifying arrowheads

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/main.go
- lib/imgbundler/imgbundler.go
- lib/imgbundler/imgbundler_test.go
- Imgs are cached for the entirety of a watch session. Flag is introduced to disable this. closes #243
- Duplicate imgs in one d2 file are only fetched once. closes #1368
> cli img fetching optimizations

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/comma-array-class.exp.json
> add class array help

- README.md
Simple documentation fix to adjust the ent2d2 community plugin URL to the correct one.
> fix(docs): correct ent2d2 url

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/url_link_non_url_tooltip_ok.exp.json
Improve tooltip URL check to ignore values without a host.
- fixes #1389 
- adds compile test, fixes test
> compiler: improve tooltip url check

- ci/release/changelogs/next.md
- d2cli/help.go
> cli: display version

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- d2graph/d2graph.go
- testdata/d2compiler/TestCompile/name-with-dot-underscore.exp.json
no longer need `EnsureChildIDVal`
closes #1398
> fix idval edge case

- d2cli/watch.go
Fixes: `d2cli/watch.go:406:21: oss.terrastruct.com/util-go/xhttp.HandlerFuncAdapter struct literal uses unkeyed fields`
> Fix: struct literal uses unkeyed fields

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/main.go
- d2plugin/exec.go
- e2etests/report/main.go
- lib/env/env.go
- lib/log/log.go
- lib/time/time.go
For very large graphs we may want to configure d2 to run longer before timing out.
- e.g. use `D2_TIMEOUT=180 d2 ...` or `d2 --timeout 180 ...` to run d2 with a timeout after 3 minutes
- also applies to plugins' layout and e2ereport
> configure timeout with D2_TIMEOUT

- ci/release/changelogs/next.md
- d2graph/d2graph.go
Fixes an issue where `Object.Text` will return the wrong font-size if called during grid-layout.
- grid object temporarily has `Children` removed during layout, causing `isContainer` to return false at that time
- TALA reads this font-size to use during layout but it was giving the wrong result
> fix grid label font size in tala

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/reserved-composite.exp.json
> fix `shape` accepting composite

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/main.go
- d2cli/static/watch.js
- d2cli/watch.go
- d2renderers/d2svg/d2svg.go
Add `--scale` flag to replace `--no-fit` (`--scale=1`) and customize zoom.
- fixes #1080 
- covers the `--no-fit` functionality from #1346 and #721 with `scale=1`
- allows users to adjust "default zoom" without relying on browser zoom
- thanks to @bluemir for initial `--no-fit` setup
> use scale flag for no-fit and customizing zoom

- d2ir/compile.go
- d2ir/import_test.go
- testdata/d2compiler/TestCompile2/vars/basic/edge-label.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/edge-map.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/nested.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/number.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/parent-scope.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/primary-and-composite.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/quoted-var.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/shape-label.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/style.exp.json
- testdata/d2compiler/TestCompile2/vars/basic/sub-array.exp.json
- testdata/d2compiler/TestCompile2/vars/boards/layer-2.exp.json
- testdata/d2compiler/TestCompile2/vars/boards/layer.exp.json
- testdata/d2compiler/TestCompile2/vars/boards/overlay.exp.json
- testdata/d2compiler/TestCompile2/vars/boards/replace.exp.json
- testdata/d2compiler/TestCompile2/vars/boards/scenario.exp.json
- testdata/d2compiler/TestCompile2/vars/override/map.exp.json
- testdata/d2compiler/TestCompile2/vars/override/recursive-var.exp.json
- testdata/d2compiler/TestCompile2/vars/override/var-in-var.exp.json
- testdata/d2ir/TestCompile/imports/vars/1.exp.json
- testdata/d2ir/TestCompile/imports/vars/2.exp.json
- testdata/d2ir/TestCompile/imports/vars/3.exp.json
If the variable is a number it should be parsed as a number and not coerced into a string. See test change.
> d2ir: Fix variables to passthrough primary type

- ci/release/changelogs/next.md
- d2cli/main.go
> ignore invalid debug flag

- ci/release/changelogs/next.md
- d2cli/main.go
- d2cli/static/watch.js
- d2cli/watch.go
- d2target/d2target.go
Let users develop multi-board diagrams in watch mode.
Example of clicking links to navigate in watch mode:
https://github.com/terrastruct/d2/assets/3120367/5dfb4e99-919b-4b6a-8ff1-7ffdd4d43738
The back button doesn't work to update the board, at least on mac. I guess it doesn't trigger a page refresh for some reason, but this can be deferred.
closes #1176
> layers support in watch mode

- ci/release/changelogs/next.md
- d2cli/fmt.go
- e2etests-cli/main_test.go
Hello! 👋
Thank you so much for `d2`, loving it so far!
Found a small bug in `d2 fmt`: If ran on multiple non-formatted files at once, it would format the 1st and exit, leaving the others non-formatted.
> fix(cli): do not exit after 1st formatted file

- .pre-commit-hooks.yaml
Add a [pre-commit](https://pre-commit.com/) hook for `d2 fmt`, usage:
```yaml
repos:
- repo: https://github.com/terrastruct/d2
rev: v0.7.0
hooks:
- id: d2-fmt
```
`pre-commit` will take care of cloning the repo, downloading `go` if needed, and building `d2`: [pre-commit.com/#golang](https://pre-commit.com/#golang)
Can be tested with:
```shell
pre-commit try-repo --all-files --ref=feat/fmt-pre-commit-hook https://github.com/maxbrunet/d2
```
_Note:_ It would be nice to have a `d2` hook to generate the diagrams, but `d2Version=` is included in the headers and requires the version `ldflag` to be set at build time which is not supported by `pre-commit`.
> feat: add d2-fmt pre-commit hook

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestDelete/scenarios-edge-inherited.exp.json
- testdata/d2oracle/TestDelete/scenarios-inherited.exp.json
If the API is used to delete an object from a board, the nulling should go at the last line, not the first. The reason is that the board may use the object in its own DSL, and adding null at the start would do nothing.
> d2oracle: nulls at end

- d2ast/d2ast.go
- d2parser/parse.go
- d2parser/parse_test.go
- testdata/d2parser/TestParse/not-amper.exp.json
> d2parser: Add not ampersand support

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/text_no_label.exp.json
Text shape labels should not be empty.
- we only validated that labels were not empty for blockstrings, but didn't validate double and single quote labels for shape `text`
- add compile test
- add validation step
> check for empty labels on text shape

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2format/format_test.go
- d2parser/parse.go
- testdata/d2compiler/TestCompile2/vars/errors/spread-mid-string.exp.json
Fixes incorrect d2fmt result with variable substitution in a string.
- Fixes #1604 
- looks like the raw string buffer wasn't reset
- adds format and compile test for this example
> fix variable substitution mid-string

- d2graph/serde.go
- d2layouts/d2layouts.go
Fixes for layout given that coreLayout may need to serialize/deserialize the graph.
- don't use old Object pointers after graph has been updated from coreLayout
- add rootLevel to graph serialization
- fix deserialization to set Object's graph reference
> layout + serialization fixes

- README.md
This PR adds [MkDocs Plugin](https://github.com/landmaj/mkdocs-d2-plugin) to the list of community plugins.
At work we are in the process of switching from PlantUML to D2 and I discovered there was no plugin for [MkDocs](https://www.mkdocs.org/), which we use to generate documentation for our clients. So I wrote one. You can see a result of using the plugin [here](https://landmaj.github.io/mkdocs-d2-plugin/).
> add MkDocs Plugin to community plugins

- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/sql-null-constraint.exp.json
Thix PR fixes issue #1655 
```d2
table: {
shape: sql_table
a: int {constraint: null}
b: int {constraint: [TRUE; False; null; NULL]}
}
```
The behavior of null, when used in arrays, is now consistent with how other types work. When used as the only constraint (without array), only types which implement `d2ast.String` are allowed. Null is also allowed but does nothing, as expected. In arrays all types are allowed but booleans are converted to lower case. Null was previously converted to an empty string, this PR changes it to lower case string "null".
This could also be fixed by changing return value of `ScalarString()` method for `Null` type. I tried it and all tests pass,  however there is this commit: https://github.com/terrastruct/d2/commit/9d0c73cef2e51da0565e09cce2b25b187cad0029 …
> fix invisible null constraints in sql_table

- lib/color/color.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance gain.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := themeColorRegex.Match([]byte("N1")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := themeColorRegex.MatchString("N1"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: oss.terrastruct.com/d2/lib/color
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 9894165	       114.3 ns/op	       2 B/op	       1 allocs/op
BenchmarkMatchString-16    	13439838	        83.61 ns/op	       0 B/op …
```
> lib/color: avoid unnecessary byte/string conversion

- d2cli/main.go
- lib/imgbundler/imgbundler.go
- lib/imgbundler/imgbundler_test.go
- lib/png/png.go
- lib/simplelog/simplelog.go
- lib/xgif/xgif.go
- lib/xgif/xgif_test.go
Update imgbundler lib functions to no longer have xmain.State as a dependency.
- adds `cacheImages` flag to `BundleLocal` and `BundleRemote` instead of reading from `ms.Env`
- updates logging to use new simplelog interface instead of ms.Log
- xmain.State shouldn't be a dependency of a lib func
> remove imgbundler's xmain.State dependency

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/no_arrowheads_in_shape.exp.json
Adds a compiler error when using `source-arrowhead` or `target-arrowhead` on a shape instead of a connection.
- fixes #1685 
- adds no_arrowheads_in_shape compiler test
> add compiler error when using arrowheads on shape

- d2renderers/d2fonts/d2fonts.go
- d2renderers/d2fonts/d2fonts_test.go
- d2renderers/d2svg/appendix/appendix.go
- lib/pdf/pdf.go
- lib/syncmap/syncmap.go
- lib/textmeasure/textmeasure.go
Updates d2fonts to not trigger races in TestCLI_E2E.
- fixes #1682 
- ran `./ci/test.sh --race ./e2etests-cli/... -count=1` 5 times successfully
- creates new SyncMap lib type as a wrapper around sync.Map
> fix d2fonts race condition in TestCLI_E2E

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- d2ir/compile.go
- d2ir/d2ir.go
- d2parser/parse.go
- testdata/d2compiler/TestCompile2/globs/double-glob-err-val.exp.json
- testdata/d2compiler/TestCompile2/globs/double-glob-override-err-val.exp.json
fixes #1676
1. This picks up refs set by globs so that the error gets the right ref.
2. Which also adds a dedupe to the compiler list of errors since keys set by globs, if errored, will report multiple errors emanating from the same range.
> compiler: Fix errors in globs

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/compile.go
- testdata/d2compiler/TestCompile2/vars/errors/split-var-usage.exp.json
- testdata/d2compiler/TestCompile2/vars/errors/undeclared-var-usage.exp.json
1. Fix missing spread substitution var
2. Change vars scoping
The compiler compiles the IR first, then resolves substitutions.
The vars stack is built-up incrementally, so a var is only visible if it's been declared before you access it.
The initial IR compilation coalesces the fields, so that x1, though accessing a var after the var's declaration, is seen as being defined before the var's declaration. 
I don't actually think in a declarative language you should be able to change vars mid-way. Changed so that all vars within the same scope are coalesced first.
closes #1641
> compiler: vars fixes

- ci/release/changelogs/next.md
- d2renderers/d2svg/appendix/appendix.go
Fixes incorrect appendix icon numbering.
- fixes #1703 
- appendix tooltip/link icons used to be replaced in the svg according to their numbered order, but the icons in the svg are ordered according to the render order
- fixes appendix creation to replace each rendered icon with the correct number icon
X is defined first so X should get 1 and Y 2, but X is rendered after Y and all the other 1st level shapes because it has to appear in front of its parent container.
Previously this meant the 1st icon in the svg was Y's icon which was incorrectly replaced with a 1 icon.
```d2
Block: {
X: {tooltip: X}
}
Y: {tooltip: Y}
```
> fix appendix icon numbering/order

- d2graph/color_helper.go
In SVG images `curentColor` is allowed as a way to explicitly inherit the current color. When setting `currentColor` as fill color on a shape together with a styling class, the class will now be used instead of the theme, which was not possible otherwise. This way you can put theme classes on shapes making them respond to dark mode. This is most useful in combination with custom themes.
> style: allow current color as valid css color

- README.md
As title suggests. Please let me know if you'd like to change anything!
> Add link to community created C# dotnet sdk

- d2graph/d2graph.go
- d2graph/layout.go
- d2layouts/d2dagrelayout/layout.go
- d2layouts/d2elklayout/layout.go
- d2layouts/d2grid/layout.go
- d2layouts/d2layouts.go
- d2layouts/d2near/layout.go
- d2layouts/d2sequence/layout.go
- d2layouts/d2sequence/layout_test.go
- d2layouts/d2sequence/sequence_diagram.go
- d2renderers/d2svg/d2svg.go
- d2target/d2target.go
- lib/label/label.go
Avoid working with label positions in memory as strings to avoid slow string comparisons.
- convert label.Position type to use int8
- `FromString(string) Position` and `String() string` for conversions
> use more efficient label position type

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/d2ir.go
- testdata/d2compiler/TestCompile2/globs/creating-node-bug.exp.json
closes #1712
before it was creating nodes unnecessarily
> d2ir: fix glob edge with common glob

- ci/release/changelogs/next.md
- d2cli/main.go
- d2cli/watch.go
- e2etests-cli/main_test.go
closes #1521
also closes #1508
> cli: watch imported files

- d2cli/main.go
- d2exporter/export_test.go
- d2graph/d2graph.go
- d2layouts/d2layouts.go
- d2lib/d2.go
- d2plugin/plugin.go
- d2plugin/plugin_features.go
Allows plugins to route cross-graph edges.
- If a plugin has the `ROUTES_EDGES` plugin feature and implements the `RoutingPlugin` interface, then it will be used for edge routing across graphs
- https://github.com/terrastruct/TALA/issues/63
> allow plugins to route cross-graph edges

- ci/release/changelogs/next.md
- d2ir/compile.go
- d2ir/filter_test.go
- testdata/d2ir/TestCompile/filters/outside-glob.exp.json
> globs: fix ampersand outside glob

- d2cli/main.go
- lib/log/log.go
This PR changes lib/log and d2cli so that the built-in log output is overridden only from d2cli only. Other use of the package lib/log will leave the built-in log output unchanged.
Closes #1680
> cli: override log output from d2cli only

- ci/release/changelogs/next.md
- d2ir/compile.go
- d2ir/import_test.go
- testdata/d2ir/TestCompile/imports/pattern-value.exp.json
> globs: fix imported case

- ci/release/changelogs/next.md
- d2target/d2target.go
- e2etests-cli/main_test.go
- e2etests-cli/testdata/TestCLI_E2E/target-nested-index.exp.svg
- e2etests-cli/testdata/TestCLI_E2E/target-nested-index2.exp.svg
Fixes a bug where the render target could be incorrect if the target path contains "index".
- fixes #1760 
- adds target-nested-index cli e2e tests
> Fix render target containing "index"

- ci/release/changelogs/next.md
- d2ir/import.go
Only occurred when using `...@` and passing in an empty path (using D2 as a library)
> fix bad import syntax edge case

- d2oracle/edit.go
- d2oracle/edit_test.go
- d2oracle/get.go
- testdata/d2oracle/TestDelete/import/3.exp.json
- testdata/d2oracle/TestSet/import/9.exp.json
> Fix d2oracle.set and d2oracle.delete on imported edges

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestDelete/import/4.exp.json
- testdata/d2oracle/TestDelete/import/5.exp.json
- testdata/d2oracle/TestDelete/import/6.exp.json
> d2oracle: fix deleting imported attributes

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestSet/edge-arrowhead-filled/1.exp.json
- testdata/d2oracle/TestSet/edge-arrowhead-filled/2.exp.json
- testdata/d2oracle/TestSet/edge-arrowhead-filled/3.exp.json
only `edge-arrowhead-filled/3` was failing, but the other 2 included for comprehensiveness
> d2oracle: fix set arrowhead fill

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/near_special.exp.json
> prevent `near` to special objects

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestDelete/import/7.exp.json
- testdata/d2oracle/TestDelete/import/8.exp.json
sometimes the object/edge is imported, but the field you are deleting is not. in those cases, the line should be deleted, not nulled
> d2oracle: fix deleting imported fields

- d2oracle/edit.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestSet/class-with-label.exp.json
- testdata/d2oracle/TestSet/edge-class-with-label.exp.json
- testdata/d2oracle/TestSet/glob-with-label.exp.json
- testdata/d2oracle/TestSet/var-with-label.exp.json
> d2oracle: fix set with classes setting labels

- d2compiler/compile_test.go
- d2renderers/d2svg/d2svg.go
- d2target/d2target.go
- testdata/d2compiler/TestCompile/shape-hierarchy.exp.json
> add shape hierarchy

- d2chaos/d2chaos.go
- d2oracle/edit.go
- d2oracle/get.go
- e2etests-cli/testdata/TestCLI_E2E/empty-base.exp.svg
> d2oracle: make get writeable refs public

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/compile.go
- d2ir/import.go
- testdata/d2compiler/TestCompile/vars-in-imports.exp.json
Turns out we can't cache the IR for imports.
The same file may be imported into different scopes, which change the substitutions of vars. But when a cache is used, the same var in the AST gets replaced.
We can probably replace these upon returning cached result, but I think it's fickle and IR compilations are fast anyway.
closes #1892
> d2ir: fix multiple substitutions in imports

- README.md
This is a plugin that allows compiling D2 blocks in markdown files into markdown/html images. I made it a while back and it's in the D2 documentation website, but I forgot to add a PR for here. Here is the PR that was accepted for d2-docs: https://github.com/terrastruct/d2-docs/pull/180
> doc: add remark-d2 to community plugins

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/import-nested-layers.exp.json
> d2compiler: fix importing nested boards

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/compile.go
- testdata/d2compiler/TestCompile/import-link-underscore.exp.json
> d2compiler: fix import underscore links

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/compile.go
- testdata/d2compiler/TestCompile/var_in_vars.exp.json
- testdata/d2compiler/TestCompile2/vars/override/recursive-var.exp.json
closes https://github.com/terrastruct/d2/issues/2017
> d2ir: use current var stack

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/sequence-diagram-icons.exp.json
closes https://github.com/terrastruct/d2/issues/2056
> d2compiler: allow children for sequence diagram image shapes

- ci/release/changelogs/next.md
- d2ir/compile.go
- d2ir/compile_test.go
- d2ir/merge.go
- testdata/d2ir/TestCompile/vars/spread-in-place.exp.json
see https://github.com/terrastruct/d2/issues/1277?notification_referrer_id=NT_kwDOAC-c77MxMTk0ODQ1NDQ3MjozMTIwMzY3#issuecomment-2288765212
after fix:
> d2ir: spread vars in place

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2graph/seqdiagram.go
- d2ir/import.go
- d2layouts/d2sequence/sequence_diagram.go
- e2etests-cli/main_test.go
- e2etests-cli/testdata/TestCLI_E2E/sequence-layer/index.exp.svg
- e2etests-cli/testdata/TestCLI_E2E/sequence-layer/seq.exp.svg
- testdata/d2compiler/TestCompile/vars-in-imports.exp.json
closes https://github.com/terrastruct/d2/issues/1692
> d2sequence: fix sequence diagrams when appearing in child boards

- ci/release/changelogs/next.md
- d2ast/keywords.go
- d2compiler/compile.go
- d2format/format.go
- d2format/format_test.go
- d2graph/d2graph.go
- d2ir/d2ir.go
- d2ir/pattern.go
- d2oracle/edit.go
- d2renderers/d2svg/d2svg.go
closes https://github.com/terrastruct/d2/issues/2018
> d2fmt: lowercase reserved keywords

- d2ir/compile.go
- d2ir/d2ir.go
- d2lsp/d2lsp.go
- d2lsp/d2lsp_test.go
> d2lsp: attach import ref

- d2compiler/compile.go
- d2oracle/edit_test.go
- testdata/d2compiler/TestCompile2/boards/isFolderOnly.exp.json
- testdata/d2oracle/TestCreate/add_layer/1.exp.json
- testdata/d2oracle/TestCreate/add_layer/3.exp.json
- testdata/d2oracle/TestCreate/add_layer/4.exp.json
- testdata/d2oracle/TestDelete/delete-layer-obj.exp.json
```d2
layers: {
c
}
```
`c` should be considered an empty folder
> better detection of empty boards

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile2/boards/board-label-primary.exp.json
- testdata/d2compiler/TestCompile2/boards/isFolderOnly.exp.json
> fix setting board label with primary

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- d2graph/d2graph.go
- testdata/d2compiler/TestCompile/no-self-link.exp.json
closes https://github.com/terrastruct/d2/issues/2202
> d2compile: invalidate self-links

- ci/release/changelogs/next.md
- d2compiler/compile.go
- d2compiler/compile_test.go
- testdata/d2compiler/TestCompile/no-class-primary.exp.json
- testdata/d2compiler/TestCompile/reserved_missing_values.exp.json
closes https://github.com/terrastruct/d2/issues/1596
> d2compiler: validate that reserved keywords have values

- d2ast/keywords.go
- d2lsp/completion.go
- d2lsp/completion_test.go
- e2etests/testdata/stable/complex-layers/dagre/board.exp.json
- e2etests/testdata/stable/complex-layers/dagre/sketch.exp.svg
- e2etests/testdata/stable/complex-layers/elk/board.exp.json
- e2etests/testdata/stable/complex-layers/elk/sketch.exp.svg
implements lsp autocomplete features to use for extensions/plugins. this pr is only keyword suggestions
> d2lsp: keyword completions

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/fmt.go
- d2cli/main.go
- e2etests-cli/main_test.go
This PR implements a `--check` flag as described in https://github.com/terrastruct/d2/issues/1180. I followed what Prettier does: it logs a warning for each unformatted file, and if any were found, it prints the number of unformatted files and a "run XYZ to fix" message.
Closes #1180.
> cli: Implement d2 fmt --check

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/export.go
- d2cli/export_test.go
- d2cli/main.go
- d2cli/watch.go
**Add --format flag to enable PNG output to stdout, allowing users to pipe D2 diagram output in PNG format to other tools.**
Changes:
- Add format flag support for PNG output to stdout
- Add test cases for format flag handling
- Update getOutputFormat to handle format flags properly
Example usage:
```
d2 input.d2 --stdout-format png -
```
Test: ./make.sh test
> cli: add format flag to support PNG output to stdout 

- README.md
Hi! I'm the author of an alternative Tree-sitter grammar, which is being developed [here](https://github.com/ravsii/tree-sitter-d2). Could we add it to the list of community projects in the `README.md`? Unfortunately, Pleshevskiy (the author of the first grammar) no longer maintains their project, it seems. 
I really appreciate that my repository was added to the official [docs](https://d2lang.com/tour/extensions/#:~:text=Tree%2Dsitter%20grammar%202%3A%20https%3A//github.com/ravsii/tree%2Dsitter%2Dd2) even before I managed to make the project fully usable, haha. While it's still a work in progress, my grammar already supports all the basic use cases for regular diagrams, SQL tables, sequence diagrams, and grid diagrams. 
Additionally, there are comparisons and installation instructions …
> docs: add alternative tree-sitter grammar

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/main.go
- d2renderers/d2svg/d2svg.go
- e2etests-cli/main_test.go
for https://github.com/terrastruct/d2/issues/2273
When outputting SVGs for HTML, you don't want the <xml> tag, which is not valid in HTML
> d2cli: --no-xml-tag

- .github/workflows/ci.yml
- ci/release/template/man/d2.1
- d2cli/main.go
- d2exporter/export_test.go
- d2renderers/d2animate/d2animate.go
- d2renderers/d2svg/appendix/appendix.go
- d2renderers/d2svg/appendix/appendix_test.go
- d2renderers/d2svg/d2svg.go
- d2target/d2target.go
- docs/examples/lib/1-d2lib/d2lib_test.go
- e2etests/e2e_test.go
closes https://github.com/terrastruct/d2/issues/2312
> add diagram hash salt

- d2cli/export.go
This pull request includes a small but important change to the `d2cli/export.go` file to handle a potential nil pointer dereference. The change ensures that the `stdoutFormatFlag` is checked for nil before dereferencing it.
* [`d2cli/export.go`](diffhunk://#diff-f588c767dfb97498969dc23064f877a228828fc086d77598633451057f703d10L27-R27): Added a nil check for `stdoutFormatFlag` before dereferencing it in the `getOutputFormat` function.
> add nil pointer check

- ci/release/changelogs/next.md
- d2renderers/d2svg/d2svg.go
- e2etests/testdata/txtar/gradient/dagre/board.exp.json
- e2etests/testdata/txtar/gradient/dagre/sketch.exp.svg
- e2etests/testdata/txtar/gradient/elk/board.exp.json
- e2etests/testdata/txtar/gradient/elk/sketch.exp.svg
- e2etests/txtar.txt
closes https://github.com/terrastruct/d2/issues/2320
> d2svg: parse connection label fill gradients

- docs/INSTALL.md
Just a small change to add references to the existing releases on scoop and chocolatey
> doc: add scoop & choco to windows install

- d2chaos/d2chaos_test.go
- d2cli/help.go
- d2cli/watch.go
- d2renderers/d2svg/dark_theme/dark_theme_test.go
- e2etests-cli/main_test.go
- e2etests/report/main.go
- go.mod
- go.sum
- lib/imgbundler/imgbundler.go
This pull request includes several changes across multiple files to improve code consistency and update dependencies. The most important changes include replacing deprecated `ioutil` package functions with their counterparts in the `os` and `io` packages, updating import paths for the `websocket` package, and updating the `go.mod` file to reflect these changes.
* [`d2chaos/d2chaos_test.go`](diffhunk://#diff-80c02cc56505c7ba69f1cd469442a09c2e10b691c5131aedd69a78cd2910e71dL93-R99): Replaced `ioutil.WriteFile` with `os.WriteFile` to write files in the `test` function.
* [`d2renderers/d2svg/dark_theme/dark_theme_test.go`](diffhunk://#diff-b8727691f6779bb6d13d8af4bcb59a0f873dea28784447d97431561490a4b5eaL452-R451): Replaced `ioutil.WriteFile` with `os.WriteFile` to write SVG files in the `run` …
> refactor: replace ioutil with os and io packages for file operations

- d2ir/compile.go
- d2oracle/edit_test.go
- testdata/d2oracle/TestDelete/underscore_linked.exp.json
first pass: replaces layer's link with "root..."
second pass: can't compile with root.
just remove the check, not doing much anyway
> d2oracle: fix delete underscore linked

- ci/release/changelogs/next.md
- d2compiler/compile.go
This PR fixes support for `center` in `d2-config` variables. Looks like it was only partially implemented but should be supported per [documentation](https://d2lang.com/tour/vars/#configuration-variables).
Test file:
```d2
vars: {
d2-config: {
center: true
}
}
x -> y
```
before change:
`preserveAspectRatio="xMinYMin meet"`
after change:
`preserveAspectRatio="xMidYMid meet"`
> compiler: support center in d2-config

- ci/release/changelogs/next.md
- lib/imgbundler/imgbundler.go
closes https://github.com/terrastruct/d2/issues/2367
> imagebundler: treat octet streams with svg signature as svg mimetypes

- ci/release/changelogs/next.md
- d2js/d2wasm/functions.go
- d2js/d2wasm/types.go
- d2js/js/README.md
- d2js/js/examples/customizable.html
Adds support for custom fonts in `d2js` by passing a byte array of the ttf file
```javascript
const result = await d2.compile(input, {
fontBold: [0, 1, 0, 0], // ... contents of .ttf file
});
const svg = await d2.render(result.diagram, result.renderOptions);
```
example screenshot of custom font:
> d2js: add support for custom fonts

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- d2ir/d2ir.go
- testdata/d2compiler/TestCompile2/globs/merge-glob-values.exp.json
- testdata/d2compiler/TestCompile2/globs/mixed-edge-quoting.exp.json
> d2ir: fix key quoting issues

- ci/release/changelogs/next.md
- d2js/js/src/worker.browser.js
- d2js/js/src/worker.node.js
- d2js/js/test/unit/basic.test.js
fixes unicode support for d2js
closes #2386 (contains screenshot of current behaviour)
Basically `btoa()` doesn't support unicode as detailed [here on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa#unicode_strings) so the unicode characters aren't decoded properly when the processing the response
I followed the approach suggested by MDN and have added in a test as well
working in browser version:
> d2js: support unicode characters

- ci/release/changelogs/next.md
- ci/release/template/man/d2.1
- d2cli/help.go
- d2cli/main.go
- d2cli/validate.go
- d2cli/watch.go
- e2etests-cli/main_test.go
> cli: add validate command

- ci/release/changelogs/next.md
- d2cli/watch.go
closes https://github.com/terrastruct/d2/issues/2131
#aireview
> cli: ignore watch events from backup files

- ci/release/changelogs/next.md
- d2parser/parse.go
- d2parser/parse_test.go
- testdata/d2parser/TestParse/import/#10.exp.json
it's almost certainly a mistake if an ID gets too long. e.g. trying to set base64 without quotes
> d2parser: impose max key length

- ci/release/changelogs/next.md
- d2compiler/compile_test.go
- lib/color/color.go
- lib/color/gradient.go
- testdata/d2compiler/TestCompile/invalid_gradient_color_stop.exp.json
Currently, D2 does not validate gradient color stops, it just renders black color in case the gradient colors are invalid.
This PR adds the functionality to validate each color stop & in case it's invalid, it throws an error.
As per D2 website `fill` & `stroke` supports css color names & hex colors apart from gradients, however inside gradient D2 supports all color formats (e.g rgb, hsl, etc), hence I used `csscolorparser` library instead of checking against `NamedColors` & `ColorHexRegex`.
`fill` docs: https://d2lang.com/tour/style#fill
/fixes #2490
> validate gradient color stops

- .pre-commit-hooks.yaml
#1528 added the `d2-fmt` hook, and with the addition of #2479, a pre-commit hook can now yield the same output as the prebuilt binaries. Without `--omit-version`, the version is slightly different: `data-d2-version="v0.7.0-HEAD"`. The end-user can always override the `entry` attribute to specify the flags as they prefer
Can be tested with:
```
pre-commit try-repo --all-files --ref=feat/d2-pre-commit-hook https://github.com/maxbrunet/d2 d2
```
> feat: add d2 pre-commit hook

- ci/release/changelogs/next.md
- d2lib/d2.go
closes https://github.com/terrastruct/d2/issues/1684
closes https://github.com/terrastruct/d2/issues/1460
> Allow custom fonts to override HandDrawn font in sketch mode

- d2cli/main.go
- d2js/d2wasm/functions.go
- d2js/js/package-lock.json
- d2js/js/package.json
- d2renderers/d2ascii/asciiroute/asciiroute.go
- d2renderers/d2ascii/asciiroute/drawing.go
- d2renderers/d2ascii/asciiroute/routing.go
- d2renderers/d2ascii/asciishapes/asciishapes.go
- d2renderers/d2ascii/asciishapes/callout.go
- d2renderers/d2ascii/asciishapes/cylinder.go
- d2renderers/d2ascii/asciishapes/diamond.go
- d2renderers/d2ascii/asciishapes/document.go
- d2renderers/d2ascii/asciishapes/rectangle.go
- d2renderers/d2ascii/asciishapes/step.go
- d2renderers/d2ascii/d2ascii.go
- e2etests/e2e_test.go
> d2ascii: remove debug logs
