README.md, ci/release/_install.sh, ci/release/template/scripts/lib.sh, docs/CONTRIBUTING.md, docs/INSTALL.md, install.sh, lib/version/version.go
=> install.sh: Add brew integration and documentation

README.md, docs/INSTALL.md
=> readme: update

.github/workflows/ci.yml
=> ci: Trigger on pull_request

README.md
=> readme: Update so library usage example is runnable

README.md
Was looking stretched on mobile.
=> readme: Example image update

lib/compress/compress.go, lib/compress/compress_test.go
necessary functions for #153 . right now this can be used by integrations. later we can figure out CLI usage
=> compress + decompress

docs/CONTRIBUTING.md
=> contributing.md: cla

ci/release/template/man/d2.1, d2parser/parse_test.go, e2etests/stable_test.go
=> Fix trailing whitespace

.github/workflows/ci.yml, .github/workflows/daily.yml, make.sh
=> make.sh: Clone submodules automatically

README.md
There's been a few comments that our comparison was buried in the FAQ
and it sort of is. It's important enough to be front and center along
with the language docs and cheat sheet.
=> README: Add comparison front and center

.github/workflows/project.yml
=> workflows/project.yml: Add all opened issues to D2 project automatically

README.md, ci/fmt.sh, ci/release/_install.sh, ci/release/changelogs/next.md, ci/release/changelogs/template.md, docs/INSTALL.md, install.sh
- docs: Defend install.sh
- INSTALL.md: Demonstrate minimal script to install standalone release
=> installsh b62b

ci/release/_install.sh, ci/release/template/scripts/lib.sh, install.sh
Will prevent red/green generated colors.
=> install.sh: hardcode header to blue

d2layouts/d2elklayout/layout.go, d2layouts/d2elklayout/setup.js
=> use Goja for elk

cmd/d2plugin-dagre/main.go, d2lib/c.go
=> remove all cgo build tags

d2compiler/compile_test.go, d2graph/d2graph.go, testdata/d2compiler/TestCompile/leaky_sequence.exp.json
=> prevent illegal sequence diagram connection

d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/underscore_unresolved_obj.exp.json
=> fix unresolved scope obj setting in compiler

ci/release/changelogs/next.md
=> prepare release changelog

ci/release/_install.sh, ci/release/build.sh, install.sh
=> install.sh: Add warning if d2 is shadowed on installation

ci/release/changelogs/next.md, docs/INSTALL.md
=> docs: Document windows installation and usage

ci/release/template/scripts/install.sh, ci/release/template/scripts/uninstall.sh
- changelogs/next.md: Fix wrapping
- release/install.sh: Install executable with .exe suffix on Windows
=> windows install e17d

ci/release/_install.sh, docs/INSTALL.md, install.sh
=> install.sh: Updates

ci/release/_build.sh, ci/release/changelogs/next.md, ci/release/template/README.md.sh, docs/INSTALL.md
=> release: On windows use .exe and alter README

d2layouts/d2dagrelayout/layout.go
See https://github.com/terrastruct/d2/pull/394#discussion_r1042504655
=> d2dagrelayout: Fix regexp

README.md
=> Add plugin links

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/constraint_label.exp.json
=> fix constraint keyword acting as label

docs/CONTRIBUTING.md
=> remove cla requirement from readme

go.mod, go.sum
https://github.com/coder/slog/commit/e4803b10ae17579e730fdfc7a70b45d29bc16b67
fixes #180
=> bump slog version

d2graph/d2graph.go, d2target/sqltable.go
We added 2 texts that we weren't measuring in https://github.com/terrastruct/d2/pull/458/files
=> update sql texts measure

README.md
=> add slack app to readme

README.md
=> add goldmark extension

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/sql-panic.exp.json
=> fix sql constraint array panic

ci/release/changelogs/next.md
=> prepare changelog

d2layouts/d2sequence/layout.go, e2etests/e2e_test.go
surface serialization bugs
implements #526
=> exercise serde

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/near_bad_connected.exp.json, testdata/d2compiler/TestCompile/near_bad_container.exp.json
=> restrict near criteria

README.md
=> add discord

README.md
=> docs: add py-d2

.prettierignore, d2renderers/d2sketch/rough.js
Update https://github.com/terrastruct/d2/pull/567 with signed commits.
=> sketch: fix regex typo in rough.js

d2plugin/exec.go
fixup https://github.com/terrastruct/d2/pull/563
=> update exec hydrate opts

d2plugin/exec.go, d2plugin/plugin.go, d2plugin/serve.go
fixup https://github.com/terrastruct/d2/pull/563
=> Include binary plugins

d2plugin/exec.go, d2plugin/plugin.go, d2plugin/serve.go, main.go
continue fixing up https://github.com/terrastruct/d2/pull/563
=> Serve layout with opts

ci/release/changelogs/next.md
=> prep changelog

ci/release/changelogs/next.md, d2renderers/d2svg/appendix/appendix.go
=> don't add appendix seperator without appendix

d2graph/d2graph.go
=> edge case: ignore empty text measurements

docs/CONTRIBUTING.md
=> add line about signing commits to CONTRIBUTING.md

d2graph/d2graph.go
fixup https://github.com/terrastruct/d2/pull/583
=> default size for no text

README.md
=> add dictim plugin

d2plugin/exec.go, d2plugin/plugin.go, help.go, lib/version/version.go, main.go
=> d2plugin: Dedup plugins array

ci/release/changelogs/next.md
=> prep 0.1.5 changelog

docs/CONTRIBUTING.md
=> add new test instructions to CONTRIBUTING.md

README.md
=> add list to readme on open-source projects using D2

README.md, ci/release/changelogs/next.md
=> prep 0.1.6 changelog

ci/release/Dockerfile, ci/release/Dockerfile_entrypoint.sh, ci/release/build.sh, ci/release/changelogs/next.md, docs/INSTALL.md, main.go
=> Dockerfile: Add playwright support for rendering PNGs

d2graph/d2graph.go, e2etests/e2e_test.go, e2etests/measured_test.go, e2etests/testdata/measured/empty-class/dagre/board.exp.json, e2etests/testdata/measured/empty-class/dagre/sketch.exp.svg, e2etests/testdata/measured/empty-shape/dagre/board.exp.json, e2etests/testdata/measured/empty-shape/dagre/sketch.exp.svg, e2etests/testdata/measured/empty-sql_table/dagre/board.exp.json, e2etests/testdata/measured/empty-sql_table/dagre/sketch.exp.svg
=> fix empty labels with class & sql_tables w/ premeasured texts

ci/release/changelogs/next.md, ci/release/template/man/d2.1, fmt.go, help.go
=> fmt: Accept multiple files to be formatted

README.md
=> add 3 new plugins

ci/release/changelogs/next.md, ci/release/template/man/d2.1, d2plugin/plugin_dagre.go, d2plugin/plugin_elk.go, help.go, main.go
... and layout links
closes #758 
closes #392
=> update CLI docs to include themes subcmd and icons link

ci/release/changelogs/next.md, ci/release/template/man/d2.1, main.go, watch.go
```
d2 --force-appendix tooltip.d2
```
both interactive & w/ appendix
closes #751
=> force appendix flag

d2chaos/d2chaos_test.go, d2ir/d2ir.go
https://github.com/terrastruct/d2/actions/runs/4140236504/jobs/7158692486#step:4:56
=> check root another way (fixes chaos test)

d2compiler/compile.go, d2graph/d2graph.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/out_of_newline_container.exp.json
=> d2oracle newline panic

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/only-underscore-nested.exp.json, testdata/d2oracle/TestDelete/only-underscore.exp.json, testdata/d2oracle/TestMove/nested-underscore-move-out.exp.json
=> d2oracle: fix delete and move with underscores

ci/release/changelogs/next.md, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/replace_dimensions.exp.json, testdata/d2oracle/TestSet/replace_position.exp.json, testdata/d2oracle/TestSet/set_dimensions.exp.json, testdata/d2oracle/TestSet/set_position.exp.json
=> d2oracle: set and replace position and dimensions

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/left.exp.json, testdata/d2oracle/TestDelete/width.exp.json
=> d2oracle: delete dimensions and positions

d2oracle/edit.go, d2oracle/edit_test.go
We considered this for edge keys, but i guess mistakenly omitted for regular keys
https://github.com/terrastruct/d2/blob/95eccae9c1a4a59037b930332d93962235541c7f/d2oracle/edit.go#L1908
=> delete id deltas reserved

d2compiler/compile.go, d2compiler/compile_test.go, d2exporter/export.go, d2graph/d2graph.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2compiler/TestCompile/path_link.exp.json, testdata/d2compiler/TestCompile/url_link.exp.json, testdata/d2oracle/TestDelete/arrowhead.exp.json, testdata/d2oracle/TestDelete/arrowhead_label.exp.json, testdata/d2oracle/TestDelete/arrowhead_map.exp.json, testdata/d2oracle/TestDelete/arrowhead_shape.exp.json, testdata/d2oracle/TestDelete/delete_icon.exp.json, testdata/d2oracle/TestDelete/edge-only-style.exp.json, testdata/d2oracle/TestSet/edge_replace_arrowhead.exp.json, testdata/d2oracle/TestSet/edge_replace_arrowhead_indexed.exp.json, testdata/d2oracle/TestSet/edge_replace_style.exp.json, testdata/d2oracle/TestSet/edge_set_arrowhead.exp.json, testdata/d2oracle/TestSet/replace_link.exp.json, testdata/d2oracle/TestSet/replace_tooltip.exp.json
=> d2oracle: arrowheads, tooltip, link

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/replace_arrowhead.exp.json, testdata/d2oracle/TestSet/replace_arrowhead_map.exp.json
=> d2oracle: replace arrowhead

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/delete_container_of_near.exp.json
=> d2oracle: fix near updating in flat map

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/chaos_1.exp.json
=> d2oracle fix delete class/table with primary

d2layouts/d2elklayout/NOTICE.txt
=> add elk version

ci/release/template/man/d2.1, main.go
=> cli: Document -dark-theme gotcha

lib/version/version.go
Update d2 version when using go install.
=> update d2 version for go install oss.terrastruct.com/d2@latest

d2cli/main.go
PDFs also need dimensions set. related #931
=> set dimensions for PDF rendering

ci/release/changelogs/next.md
=> changelog #941

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/conflicts_generated_continued.exp.json
=> delete hoisting children should ignore parent id

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/drop_value.exp.json, testdata/d2oracle/TestDelete/drop_value_with_primary.exp.json, testdata/d2oracle/TestDelete/save_map.exp.json, testdata/d2oracle/TestDelete/save_map_with_primary.exp.json
=> d2oracle: fix 2 bugs with deletion

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/edge_invalid_style.exp.json, testdata/d2compiler/TestCompile/obj_invalid_style.exp.json
=> give err msg for invalid edge style

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/unsemantic_markdown.exp.json, testdata/d2compiler/TestCompile/unsemantic_markdown_2.exp.json
=> validate markdown

d2plugin/plugin_dagre.go
didn't deeply inspect, just fixing the reported errors with what seems like a harmless straightfwd way
=> Fix cli race

ci/release/changelogs/next.md, go.mod, go.sum
=> bump go-util

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/chaos_1.exp.json, testdata/d2oracle/TestDelete/class_refs.exp.json, testdata/d2oracle/TestDelete/shape_class.exp.json, testdata/d2oracle/TestDelete/shape_sql_table.exp.json, testdata/d2oracle/TestDelete/table_refs.exp.json
=> d2oracle: delete class and table deletes all refs

d2ast/d2ast.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/duplicate.exp.json
=> fix d2oracle move with duplicates

d2layouts/d2sequence/sequence_diagram.go, d2parser/parse.go, d2plugin/exec.go, d2plugin/plugin.go, lib/geo/bezier.go, lib/geo/segment.go, lib/shape/shape.go, lib/textmeasure/textmeasure.go
Lint all files for go 1.20
- related #1020
=> lint for go 1.20

lib/geo/point.go
Updating geo.Point.OnSegment to run faster and to clarify it is for horizontal or vertical segments.
- remove extra math.Max and math.Min calls
- rename for clarity
=> cleanup and optimization for Point.OnSegment

d2graph/d2graph.go
=> fix apply theme to measured

d2plugin/exec.go, d2plugin/plugin.go, go.mod, go.sum
going to use it for multiple tala seeds
=> cli: support int64 slice

ci/release/changelogs/next.md, d2cli/watch.go
=> fix watch title

ci/release/changelogs/next.md, d2cli/main.go, lib/background/background.go, lib/png/png.go
closes #1057
closes #271
closes #915
=> print msg when png or layout takes a long time

d2oracle/edit.go, d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestMove/container_conflicts_generated.exp.json
move id delta wasn't matching what move actually changed
=> fix move id delta

d2oracle/edit.go, d2oracle/edit_test.go
followup to https://github.com/terrastruct/d2/pull/1067
moveiddelta should always match move
=> fix id delta

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/duplicate_generated.exp.json
=> fix move with child and container same id

d2graph/d2graph.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/duplicate_generated.exp.json
followup to https://github.com/terrastruct/d2/pull/1072 handling deletion (previous one only handled moves)
=> Fix generated containers delete

.gitignore
=> .gitignore: Ensure no .got files are committed.

README.md
see the preview: https://github.com/golang-queue
=> docs(readme): add golang queue library as example.

README.md
Related https://github.com/terrastruct/d2-docs/pull/102
=> Add d2-filter as community plugin

d2cli/main.go, d2graph/d2graph.go
regression from https://github.com/terrastruct/d2/commit/c8dc0f94a249c8ba1d3d4f416636f508948471ed
=> fix watch mode

d2compiler/compile_test.go, d2graph/d2graph.go, testdata/d2compiler/TestCompile/text-transform.exp.json
=> add text-transform as keyword

ci/release/changelogs/v0.4.0.md
You should also change it in the latest release
=> fix urls in changelogs

ci/release/changelogs/next.md, d2cli/main.go
=> link with relative paths

d2ir/d2ir.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/classes-style.exp.json, testdata/d2oracle/TestSet/dupe-classes-style.exp.json, testdata/d2oracle/TestSet/unapplied-classes-style-2.exp.json, testdata/d2oracle/TestSet/unapplied-classes-style.exp.json
when modifying object/edge attributes, classes should not be touched. see tests
closes #1202
=> d2oracle: don't modify classes

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile/class-shape-class.exp.json
=> fix classes panic

d2plugin/plugin_features.go, e2etests/stable_test.go, e2etests/todo_test.go
=> add more detailed error msg for layout-specific err

.gitignore, e2etests/report/main.go
Profile e2e test cpu/memory usage with `-cpuprofile` or `-memprofile`.
=> add profiling for e2e tests

d2renderers/d2sketch/sketch_test.go
=> add d2sketch in ci

d2compiler/compile_test.go, d2parser/parse.go, testdata/d2compiler/TestCompile/md_block_string_err.exp.json
=> add md block info

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestReconnectEdge/basic.exp.json, testdata/d2oracle/TestReconnectEdge/both.exp.json, testdata/d2oracle/TestReconnectEdge/contained.exp.json, testdata/d2oracle/TestReconnectEdge/in_chain_3.exp.json, testdata/d2oracle/TestReconnectEdge/in_chain_4.exp.json, testdata/d2oracle/TestReconnectEdge/indexed_ref.exp.json, testdata/d2oracle/TestReconnectEdge/loop.exp.json, testdata/d2oracle/TestReconnectEdge/middle_chain.exp.json, testdata/d2oracle/TestReconnectEdge/middle_chain_both.exp.json, testdata/d2oracle/TestReconnectEdge/middle_chain_first.exp.json, testdata/d2oracle/TestReconnectEdge/middle_chain_last.exp.json, testdata/d2oracle/TestReconnectEdge/middle_chain_src.exp.json, testdata/d2oracle/TestReconnectEdge/missing_params.exp.json, testdata/d2oracle/TestReconnectEdge/nonexistant_edge.exp.json, testdata/d2oracle/TestReconnectEdge/nonexistant_obj.exp.json, testdata/d2oracle/TestReconnectEdge/reverse.exp.json, testdata/d2oracle/TestReconnectEdge/scope_inner.exp.json, testdata/d2oracle/TestReconnectEdge/scope_outer.exp.json, testdata/d2oracle/TestReconnectEdge/second_index.exp.json, testdata/d2oracle/TestReconnectEdge/src.exp.json
Also implements the Delta properly (previous version was half assed)
closes #637
=> d2oracle.ReconnectEdge

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestReconnectEdge/bad_params.exp.json, testdata/d2oracle/TestReconnectEdge/preserve_old_obj.exp.json
slightly fixes https://github.com/terrastruct/d2/pull/1272 to be more robust with params
=> ReconnectEdge minor fix

d2oracle/edit.go, d2oracle/edit_test.go
fixing https://github.com/terrastruct/d2/pull/1272 again
=> use correct keys for nested

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestReconnectEdge/bad_params.exp.json, testdata/d2oracle/TestReconnectEdge/missing_params.exp.json
patching https://github.com/terrastruct/d2/pull/1272
instead of erroring, just ignore if no new endpoints
=> ignore when no params

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_edge_ref_1.exp.json, testdata/d2oracle/TestMove/include_descendants_edge_ref_2.exp.json, testdata/d2oracle/TestMove/include_descendants_edge_ref_3.exp.json, testdata/d2oracle/TestMove/include_descendants_edge_ref_4.exp.json, testdata/d2oracle/TestMove/include_descendants_edge_ref_5.exp.json, testdata/d2oracle/TestMove/include_descendants_flat_1.exp.json, testdata/d2oracle/TestMove/include_descendants_flat_2.exp.json, testdata/d2oracle/TestMove/include_descendants_flat_3.exp.json, testdata/d2oracle/TestMove/include_descendants_flat_4.exp.json, testdata/d2oracle/TestMove/include_descendants_map_1.exp.json, testdata/d2oracle/TestMove/include_descendants_map_2.exp.json, testdata/d2oracle/TestMove/include_descendants_nested_1.exp.json, testdata/d2oracle/TestMove/include_descendants_nested_2.exp.json
patching https://github.com/terrastruct/d2/pull/1304
=> fixing move with container

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_edge_ref_6.exp.json
patching https://github.com/terrastruct/d2/pull/1304
=> patch move container

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_edge_ref_7.exp.json
patches https://github.com/terrastruct/d2/pull/1304
=> patching move containers

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/conflicts_generated_3.exp.json
=> Fix delete generated edge case

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_nested_reserved_2.exp.json, testdata/d2oracle/TestMove/include_descendants_nested_reserved_3.exp.json, testdata/d2oracle/TestMove/nested_reserved_2.exp.json, testdata/d2oracle/TestMove/nested_reserved_3.exp.json, testdata/d2oracle/TestMove/slice_style.exp.json
=> d2oracle: fix reserved splitting

d2ast/d2ast.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_underscore.exp.json
patching https://github.com/terrastruct/d2/pull/1304
also minor patch to MapKey.Equals that reduces unnecessary repetition
=> fix underscore edge case container move

d2oracle/get.go
=> d2oracle: GetChildrenIDs

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_move_out.exp.json
patching https://github.com/terrastruct/d2/pull/1304
=> d2oracle: fix map carry

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_underscore_regression.exp.json, testdata/d2oracle/TestMove/underscore_regression.exp.json
=> d2oracle: fix underscore regression

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/include_descendants_underscore_regression_2.exp.json
=> d2oracle: fix underscore

d2oracle/get.go
=> d2oracle get obj order

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestMove/underscore_edge_container_6.exp.json
=> fix underscore move

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestRename/errors/nonexistent.exp.json
also does some more checks in test and fixes an err msg
=> d2oracle: return newkey in rename

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestRename/generated-conflict.exp.json
=> d2oracle: fix RenameIDDelta with generated conflict

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, e2etests/measured_test.go, e2etests/regression_test.go, testdata/d2compiler/TestCompile/no_empty_block_string.exp.json, testdata/d2compiler/TestCompile/no_empty_block_strings.exp.json, testdata/d2compiler/TestCompile/no_new_lines_only_block_string.exp.json, testdata/d2compiler/TestCompile/no_white_spaces_only_block_string.exp.json
Throw a compiler error for empty block strings.
=> compile: no empty block strings

d2compiler/compile.go, d2format/format.go, d2format/format_test.go, d2ir/import.go, d2parser/parse.go
See individual PRs.
Closes #1388
=> Import fixes

d2graph/d2graph.go, d2lib/d2.go
pass in filesystem to compile options
=> Texts() recursively

d2oracle/edit_test.go, d2oracle/get.go
=> d2oracle: simplify board paths

d2oracle/get.go
=> d2oracle: update getters w/ boardPath

d2compiler/compile.go, d2compiler/compile_test.go, d2graph/d2graph.go, testdata/d2compiler/TestCompile/icon-near-composite-together.exp.json, testdata/d2compiler/TestCompile/label-near-composite-separate.exp.json, testdata/d2compiler/TestCompile/label-near-composite-together.exp.json, testdata/d2compiler/TestCompile/label-near-invalid-edge.exp.json, testdata/d2compiler/TestCompile/label-near-invalid-field.exp.json, testdata/d2compiler/TestCompile/label-near-parent.exp.json
see tests. only compiling, not used
for https://github.com/terrastruct/d2/issues/1423
=> label and icon position attributes

d2compiler/compile.go, d2graph/d2graph.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestReconnectEdge/layers-basic.exp.json, testdata/d2oracle/TestReconnectEdge/scenarios-basic.exp.json, testdata/d2oracle/TestReconnectEdge/scenarios-chain.exp.json, testdata/d2oracle/TestReconnectEdge/scenarios-outer-scope.exp.json, testdata/d2oracle/TestRename/layers-basic.exp.json, testdata/d2oracle/TestRename/scenarios-basic.exp.json, testdata/d2oracle/TestRename/scenarios-conflict.exp.json, testdata/d2oracle/TestRename/scenarios-scope-err.exp.json, testdata/d2oracle/TestSet/scenarios-arrowhead.exp.json, testdata/d2oracle/TestSet/scenarios-edge-set.exp.json, testdata/d2oracle/TestSet/scenarios-existing-edge-set.exp.json
- ReconnectEdge, and its delta API
- Rename, and its delta API
- Set on edge
=> d2oracle boardPath updates

d2oracle/edit.go, d2oracle/edit_test.go
=> DeleteIDDeltas with boardPath

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/scenarios-edge-inherited.exp.json, testdata/d2oracle/TestDelete/scenarios-inherited.exp.json
=> set to null to delete out of scope

d2compiler/compile.go, d2compiler/compile_test.go, d2graph/d2graph.go, testdata/d2compiler/TestCompile/portal.exp.json
implements keyword for #1456
Doesn't do anything with it yet
=> compiler: portal keyword

d2compiler/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile2/nulls/implicit/delete-multiple-connections.exp.json
addressing https://github.com/terrastruct/d2/pull/1446#pullrequestreview-1510334126
=> null pr fixes

d2ir/compile.go, e2etests-cli/main_test.go, e2etests-cli/testdata/TestCLI_E2E/layer-link/index.exp.svg, e2etests-cli/testdata/TestCLI_E2E/layer-link/test2.exp.svg
=> fix nested links imported

.github/workflows/daily.yml, ci/test.sh, make.sh
=> ci: Fix daily part 2

d2cli/fmt.go, e2etests-cli/main_test.go
=> fmt cli test

d2compiler/compile.go, d2graph/d2graph.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/import/1.exp.json
=> d2oracle support imports

d2oracle/edit.go, d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestSet/import/2.exp.json, testdata/d2oracle/TestSet/import/3.exp.json
=> d2oracle fix imports

d2ir/compile.go, testdata/d2compiler/TestCompile/link-board-key-nested.exp.json, testdata/d2compiler/TestCompile/link-board-mixed.exp.json, testdata/d2compiler/TestCompile/link-board-nested.exp.json, testdata/d2compiler/TestCompile/link-board-ok.exp.json, testdata/d2compiler/TestCompile/link-board-underscore.exp.json, testdata/d2ir/TestCompile/imports/boards.exp.json
=> dont modify ast when modifying links in the IR

ci/release/changelogs/next.md, d2cli/main.go
=> cli: include input path name in failure msg

ci/release/build_in_docker.sh, d2plugin/plugin.go
=> bump go version in docker

.github/workflows/ci.yml
Adds a clear check for commit signatures.
- this will allow missing commit signatures to be clearly seen in the list of checks on PRs
=> workflow check for commit signatures

ci/release/changelogs/next.md
=> changelog #1681

d2cli/watch.go
=> fix watch race

d2compiler/compile.go, d2ir/compile.go, d2ir/compile_test.go, d2oracle/edit.go
=> expose import stack

d2ir/compile.go, d2ir/import.go
https://github.com/terrastruct/d2/pull/1789
=> amend expose imports

d2oracle/edit.go, d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestSet/import/1.exp.json, testdata/d2oracle/TestSet/import/2.exp.json, testdata/d2oracle/TestSet/import/3.exp.json, testdata/d2oracle/TestSet/import/4.exp.json, testdata/d2oracle/TestSet/import/5.exp.json, testdata/d2oracle/TestSet/import/6.exp.json
=> d2oracle set imports

d2graph/d2graph.go, d2oracle/edit.go, d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestSet/import/7.exp.json, testdata/d2oracle/TestSet/scenarios-multiple.exp.json
=> D2oracle set imports again

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/import/1.exp.json, testdata/d2oracle/TestDelete/import/2.exp.json
=> d2oracle: handle deleting imported shape

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile2/nulls/implicit/delete-nested-connection.exp.json
=> fix nested connection implicit delete

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/label-near/1.exp.json, testdata/d2oracle/TestSet/label-near/2.exp.json, testdata/d2oracle/TestSet/label-near/3.exp.json, testdata/d2oracle/TestSet/label-near/4.exp.json, testdata/d2oracle/TestSet/label-near/5.exp.json
=> d2oracle: fix label near setting

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/boards/no-inherit-label.exp.json
If you give your scenario a label, you don't want all steps in a scenario to be labeled the same.
closes #1837
=> boards don't inherit label

e2etests/report/main.go
=> add test name flag to test report

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/edge-arrowhead-filled/4.exp.json, testdata/d2oracle/TestSet/edge-arrowhead-filled/5.exp.json
=> followup fix to https://github.com/terrastruct/d2/pull/1847

d2graph/d2graph.go
amend https://github.com/terrastruct/d2/pull/1869
=> treat hierarchy same as rect

d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/fixed-pos-shape-hierarchy.exp.json
=> validate position keyword compatibility

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/delete-imported-layer-obj.exp.json, testdata/d2oracle/TestDelete/delete-layer-obj.exp.json, testdata/d2oracle/TestDelete/delete-layer-style.exp.json, testdata/d2oracle/TestDelete/delete-not-layer-obj.exp.json
=> d2oracle: fix deleting nested board field

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/delete-theme-set.exp.json, testdata/d2oracle/TestDelete/delete-theme-set/1.exp.json, testdata/d2oracle/TestDelete/delete-theme-set/2.exp.json
=> d2oracle: delete theme-set

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/nested-edge-chained.exp.json, testdata/d2oracle/TestSet/nested-edge-chained/1.exp.json, testdata/d2oracle/TestSet/nested-edge-chained/2.exp.json
=> d2oracle: fix setting edge in an edge case

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile2/vars/basic/double-border.exp.json, testdata/d2compiler/TestCompile2/vars/basic/invalid-double-border.exp.json
=> fix case-sensitive validations

go.mod, go.sum
hopefully fix https://github.com/terrastruct/d2/issues/1767
=> upgrade fsnotify

ci/release/aws/ensure.sh
=> ci/release: update windows script

ci/release/build_in_docker.sh
=> upgrade go version in docker

ci/release/build_in_docker.sh, d2graph/serde.go, d2plugin/exec.go, d2plugin/plugin.go, d2plugin/serve.go
fixing https://github.com/terrastruct/d2/pull/1742
=> Fix routing plugin

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/edge-comment.exp.json
=> d2oracle: fix setting with comments

d2cli/main.go, docs/CONTRIBUTING.md, lib/urlenc/urlenc_test.go
=> chore: fix some typos

README.md
=> readme: update notable

lib/imgbundler/imgbundler.go
closes https://github.com/terrastruct/d2/issues/1434
=> do not run imgbundler unnecessarily

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestDelete/edge-in-layer.exp.json, testdata/d2oracle/TestDelete/edge-out-layer.exp.json
=> d2oracle: fix edge delete reserve in layer

d2chaos/d2chaos.go, d2ir/compile.go, d2ir/pattern_test.go, testdata/d2ir/TestCompile/patterns/edge-glob-null.exp.json
=> d2oracle: glob null edges

d2compiler/compile.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/scenario-child.exp.json, testdata/d2oracle/TestSet/scenario-grandchild.exp.json
=> d2oracle: set edge property on scenario grandchild

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/spread-import-link.exp.json
=> compiler: fix board links from spread imports

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-link-underscore.exp.json
followup https://github.com/terrastruct/d2/pull/1999
=> d2compiler: fix underscore sibling edge case

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/multiple-import-nested-layers.exp.json
followup https://github.com/terrastruct/d2/pull/1998
=> d2compiler: fix nested import edge case

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/link-file-underscore.exp.json
=> fix import underscore links

ci/release/changelogs/next.md, d2ast/d2ast.go, d2format/format.go, d2format/format_test.go, d2ir/compile.go, d2ir/filter_test.go, testdata/d2ir/TestCompile/filters/errors/not-basic.exp.json, testdata/d2ir/TestCompile/filters/not-basic.exp.json
see https://github.com/terrastruct/d2/issues/1567
=> inverse filter

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, d2parser/parse.go, testdata/d2compiler/TestCompile2/globs/exists-filter.exp.json, testdata/d2compiler/TestCompile2/globs/glob-filter.exp.json, testdata/d2oracle/TestSet/edge-arrowhead-filled/2.exp.json
closes https://github.com/terrastruct/d2/issues/1567
=> allow pattern globs in values

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/invalid-link-1.exp.json, testdata/d2compiler/TestCompile/invalid-link-2.exp.json, testdata/d2compiler/TestCompile/invalid-link.exp.json
=> d2ir: fix link panic

d2compiler/compile_test.go, d2ir/compile.go, e2etests-cli/testdata/TestCLI_E2E/layer-link/index.exp.svg, e2etests-cli/testdata/TestCLI_E2E/layer-link/test2.exp.svg, testdata/d2compiler/TestCompile/import-link-underscore-1.exp.json, testdata/d2compiler/TestCompile/import-link-underscore-2.exp.json
=> fix non-spread import links

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/double-glob-second-scenario.exp.json, testdata/d2compiler/TestCompile2/globs/reapply-scenario.exp.json, testdata/d2compiler/TestCompile2/globs/second-scenario.exp.json, testdata/d2ir/TestCompile/patterns/alixander-review/5.exp.json, testdata/d2ir/TestCompile/patterns/double-glob/defaults.exp.json
=> d2ir: fix glob applications to multiple scenarios

ci/release/build.sh
=> ci: build locally

ci/release/build.sh
followup https://github.com/terrastruct/d2/pull/2033
=> ci: build docker local

ci/release/build.sh
=> ci: revert local docker

ci/release/docker/Dockerfile
=> ci: update docker node

ci/release/changelogs/next.md, d2cli/main.go, d2cli/watch.go, e2etests-cli/main_test.go
closes https://github.com/terrastruct/d2/issues/2023
=> d2cli: fix watch mode back links

ci/release/changelogs/next.md, d2ast/d2ast.go, d2ir/compile.go, e2etests-cli/main_test.go, e2etests-cli/testdata/TestCLI_E2E/import_icon_relative.exp.svg
closes https://github.com/terrastruct/d2/issues/2059
=> d2ir: fix local icon imports from files that are imported

ci/release/changelogs/next.md, d2cli/watch.go, e2etests-cli/main_test.go
closes https://github.com/terrastruct/d2/issues/1880
=> cli: fix nested layer navigation in watch mode

ci/release/changelogs/next.md, ci/release/template/man/d2.1, d2cli/main.go, d2renderers/d2animate/d2animate.go
closes https://github.com/terrastruct/d2/issues/2067
closes https://github.com/terrastruct/d2/issues/2068
=> d2cli: fix theme passing to gif, fix scale on animated svg

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-link-layer-1.exp.json, testdata/d2compiler/TestCompile/import-link-layer-2.exp.json, testdata/d2compiler/TestCompile/import-link-layer-3.exp.json, testdata/d2compiler/TestCompile/import-link-layer-4.exp.json, testdata/d2compiler/TestCompile/import-link-sibling-layer.exp.json, testdata/d2compiler/TestCompile/link-board-underscore-not-found.exp.json
closes https://github.com/terrastruct/d2/issues/2074
=> d2ir: enable linking beyond board root

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-icon-near.exp.json
patches https://github.com/terrastruct/d2/pull/2066
=> fix importing icon.near field

d2compiler/compile.go, d2compiler/compile_test.go, testdata/d2compiler/TestCompile/link-board-not-board.exp.json, testdata/d2compiler/TestCompile/link-board-not-found.exp.json, testdata/d2compiler/TestCompile/link-board-underscore-not-found.exp.json
as a result of https://github.com/terrastruct/d2/pull/2075 , board links are allowed to be unfound
=> allow unfound boards

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-link-underscore-3.exp.json
fixup https://github.com/terrastruct/d2/pull/2075
=> fix chained imports and underscore links

d2cli/main.go
closes https://github.com/terrastruct/TALA/issues/85
=> fix rendering animated svg with plugins

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, d2ir/filter_test.go, testdata/d2compiler/TestCompile2/globs/default-glob-filter.exp.json, testdata/d2compiler/TestCompile2/globs/default-glob-filter/1.exp.json, testdata/d2compiler/TestCompile2/globs/default-glob-filter/2.exp.json, testdata/d2compiler/TestCompile2/globs/default-glob-filter/3.exp.json, testdata/d2compiler/TestCompile2/globs/default-glob-filter/4.exp.json, testdata/d2ir/TestCompile/filters/lazy-filter.exp.json
closes https://github.com/terrastruct/d2/issues/2027
=> globs: filter interoperability with defaults

ci/release/changelogs/next.md, d2ir/import.go, d2ir/import_test.go
closes https://github.com/terrastruct/d2/issues/1397
=> d2ir: allow absolute imports

go.mod
closes https://github.com/terrastruct/d2/issues/2126
=> remove replace directive

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go, lib/memfs/memfs.go
=> d2lsp: GetFieldRefs

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go, lib/memfs/memfs.go
=> amend lsp refs

d2ir/d2ir.go, d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> support board path

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> getrefs support edges

d2compiler/compile.go, d2compiler/compile_test.go, d2ir/compile.go, d2target/d2target.go, testdata/d2compiler/TestCompile2/vars/config/data.exp.json
=> pass arbitrary vars

d2compiler/compile.go, d2compiler/compile_test.go, d2graph/d2graph.go, d2lib/d2.go, d2target/d2target.go, testdata/d2compiler/TestCompile2/vars/config/data.exp.json
=> pass arbitrary data to graph

d2ast/d2ast.go, d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> d2lsp: implement GetImportRanges

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> no need to pass fs

d2ir/compile.go, d2lsp/d2lsp_test.go
=> set import ast more precisely

README.md, d2format/format.go, d2format/format_test.go, d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestCreate/add_layer/1.exp.json, testdata/d2oracle/TestCreate/add_layer/2.exp.json, testdata/d2oracle/TestCreate/add_layer/3.exp.json
also formatter changed to not add indents in the empty line before board nodes
=> d2oracle: create board

ci/release/changelogs/next.md, d2format/format.go, d2format/format_test.go
closes https://github.com/terrastruct/d2/issues/2177
=> d2fmt: remove empty board keywords

d2ir/d2ir.go, d2lsp/d2lsp_test.go
=> d2lsp: fix nested board finding

lib/shape/shape_circle.go
=> fix circle fit again

d2graph/serde.go
=> serialize data var

ci/release/changelogs/next.md, d2ir/compile.go, e2etests-cli/main_test.go, e2etests-cli/testdata/TestCLI_E2E/chain_icon_import.exp.svg
closes https://github.com/terrastruct/d2/issues/2191
=> d2ir: fix icon substitutions

d2ast/d2ast.go, d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> d2lsp: get board at position

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> fix d2lsp pr

d2lsp/d2lsp.go, d2lsp/d2lsp_test.go
=> d2lsp: getboardatposition edge case

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestSet/labeled_set_position.exp.json
=> fix set with explicit label

ci/release/changelogs/next.md, d2compiler/compile_test.go, lib/textmeasure/links.go, lib/textmeasure/markdown.go, testdata/d2compiler/TestCompile/markdown_ampersand.exp.json
closes https://github.com/terrastruct/d2/issues/1898
=> markdown: sanitize links

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/non_url_link.exp.json
closes https://github.com/terrastruct/d2/issues/2237
=> compiler: allow non-http scheme url links

d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestSet/step-connection.exp.json
=> d2oracle: exclude edges from writeable object refs

d2ir/compile.go, d2oracle/edit_test.go, testdata/d2oracle/TestCreate/add_layer/5.exp.json
=> d2compiler: allow empty layers fix

ci/release/template/man/d2.1
closes https://github.com/terrastruct/d2/issues/112
=> man: document environment variables

docs/examples/lib/1-d2lib/d2lib.go, docs/examples/lib/2-d2oracle/d2oracle.go, docs/examples/lib/3-lowlevel/lowlevel.go
closes https://github.com/terrastruct/d2/issues/2258
=> docs: update lib examples with proper context logging

d2lsp/completion.go, d2lsp/completion_test.go
=> d2lsp: fix nested style map

d2js/js/ci/build.sh, d2js/js/package.json
=> d2js: NPM polish

d2js/js/Makefile, d2js/js/README.md, d2js/js/dev-server.js, d2js/js/examples/customizable.html
=> d2js: dev server changes

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/connected-filter.exp.json, testdata/d2compiler/TestCompile2/globs/leaf-filter.exp.json
closes https://github.com/terrastruct/d2/issues/2010
=> globs: add filters

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile2/nulls/basic/basic-edge.exp.json, testdata/d2compiler/TestCompile2/nulls/basic/nested-edge.exp.json
closes https://github.com/terrastruct/d2/issues/2318
=> d2ir: fix deleting nested edge

ci/release/changelogs/next.md, d2themes/d2themescatalog/buttered_toast.go, d2themes/d2themescatalog/colorblind_clear.go, d2themes/d2themescatalog/cool_classics.go, d2themes/d2themescatalog/default.go, d2themes/d2themescatalog/earth_tones.go, d2themes/d2themescatalog/everglade_green.go, d2themes/d2themescatalog/grape_soda.go, d2themes/d2themescatalog/mixed_berry_blue.go, d2themes/d2themescatalog/orange_creamsicle.go, d2themes/d2themescatalog/shirley_temple.go, d2themes/d2themescatalog/vanilla_nitro_cola.go
closes https://github.com/terrastruct/d2/issues/2277
=> code: consistent theme name casing

d2js/d2wasm/functions.go
=> d2js: JSONify compile err msg

d2compiler/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile2/globs/leaf-filter-1.exp.json, testdata/d2compiler/TestCompile2/globs/leaf-filter-2.exp.json
=> fix &leaf filter

d2cli/main.go
Changed
> (default localhost:0, which **is** will open on a randomly available local port)
into
> (default localhost:0, which will open on a randomly available local port)
=> chore: fix a typo

docs/examples/wcc/wcc.d2
https://github.com/terrastruct/d2/actions/runs/13314008710/job/37183434190
=> fmt example

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/vars/basic/comment-array.exp.json
=> d2ir: do not interpret comment in array as array node

d2ast/keywords.go, d2compiler/compile.go, d2compiler/compile_test.go, d2exporter/export.go, d2graph/d2graph.go, d2target/d2target.go, testdata/d2compiler/TestCompile2/globs/legend-label.exp.json
=> add legend-label

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/edge-glob-ampersand-filter/1.exp.json, testdata/d2compiler/TestCompile2/globs/edge-glob-ampersand-filter/2.exp.json
closes https://github.com/terrastruct/d2/issues/2363
=> d2ir: add support for nested property filtering on edges

d2compiler/compile.go, d2compiler/compile_test.go, d2graph/d2graph.go, testdata/d2compiler/TestCompile2/globs/md-shape.exp.json
fixes https://github.com/terrastruct/d2/issues/2396
=> patch md label setting

d2format/format.go
=> Fix suspend value handling in format.go by adding Suspension case

d2compiler/compile_test.go, d2ir/compile.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile2/globs/suspend-shape.exp.json, testdata/d2compiler/TestCompile2/globs/unsuspend-edge-label.exp.json, testdata/d2compiler/TestCompile2/globs/unsuspend-label.exp.json, testdata/d2compiler/TestCompile2/globs/unsuspend-shape-label.exp.json
=> `suspend` fixes

README.md
Add link to rehype plugin (uses WASM)
=> Add link to Rehype plugin

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-var-chain.exp.json
=> fix import var panic

ci/release/changelogs/next.md, d2js/js/index.d.ts, d2js/js/package.json
attempt for https://github.com/terrastruct/d2/issues/2286
all credits go to @hpr1999
=> TypeScript signatures

ci/release/changelogs/next.md, d2compiler/compile.go, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/url_relative_link.exp.json
closes https://github.com/terrastruct/d2/issues/2357
=> d2ir: allow root URL paths

.github/workflows/daily.yml, d2js/js/README.md, d2js/js/ci/build.sh, d2js/js/package.json
closes https://github.com/terrastruct/d2/issues/2433
closes https://github.com/terrastruct/d2/issues/2385
=> d2js nightly ci

.github/workflows/daily.yml, README.md, ci/release/release-js.sh, ci/release/release.sh, d2js/js/ci/build.sh, d2js/js/package.json
closes https://github.com/terrastruct/d2/issues/2290
when release script runs, a new `npm-version` flag must be specified, which will update the npm version's latest to it.
=> ci release include d2js

d2js/js/README.md
=> add val link

d2js/js/CHANGELOG.md, d2js/js/index.d.ts, d2js/js/package.json
I missed small things in the first PR. Some follow up fixes
=> Fix TypeScript signatures

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/glob-spread-vars.exp.json, testdata/d2compiler/TestCompile/glob-spread-vars/1.exp.json, testdata/d2compiler/TestCompile/glob-spread-vars/2.exp.json
closes https://github.com/terrastruct/d2/issues/2426
=> d2compiler: fix globs applying to spread vars

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, d2ir/compile_test.go, d2ir/d2ir.go, testdata/d2compiler/TestCompile/image_children_Steps.exp.json, testdata/d2compiler/TestCompile/import-classes-boards.exp.json
=> d2ir: fix classes panic

.github/workflows/daily.yml
=> export var

.github/workflows/daily.yml
=> fix nightly npm

.github/workflows/daily.yml, Makefile, d2js/js/ci/build.sh, d2js/js/make.sh
=> Debug nightly

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/var_nested_in_markdown.exp.json
closes https://github.com/terrastruct/d2/issues/2450
=> fix markdown nested variables

.github/workflows/daily.yml, Makefile, d2js/js/ci/build.sh, d2js/js/make.sh
=> add daily debug logs back

.github/workflows/daily.yml, Makefile, d2js/js/ci/build.sh, d2js/js/make.sh
=> remove logs

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-scenario.exp.json, testdata/d2compiler/TestCompile/import-steps.exp.json
closes https://github.com/terrastruct/d2/issues/2449
=> fix scenario/step import

ci/release/changelogs/next.md, d2format/format.go, d2format/format_test.go
closes https://github.com/terrastruct/d2/issues/2447
=> fix vars fmt

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/import-connections.exp.json, testdata/d2compiler/TestCompile/import-icon-near.exp.json, testdata/d2compiler/TestCompile/import-style-1.exp.json, testdata/d2compiler/TestCompile/import-style-2.exp.json, testdata/d2compiler/TestCompile/import-style.exp.json, testdata/d2ir/TestCompile/imports/boards-deep.exp.json, testdata/d2ir/TestCompile/imports/boards.exp.json, testdata/d2ir/TestCompile/imports/nested/array.exp.json, testdata/d2ir/TestCompile/imports/nested/map.exp.json, testdata/d2ir/TestCompile/imports/nested/scalar.exp.json, testdata/d2ir/TestCompile/imports/pattern-value.exp.json, testdata/d2ir/TestCompile/imports/steps-inheritence.exp.json, testdata/d2ir/TestCompile/imports/value.exp.json, testdata/d2oracle/TestSet/import/6.exp.json
closes https://github.com/terrastruct/d2/issues/2463
=> d2ir: apply current scope to imported fields/edges

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestCreate/image-edge.exp.json
=> d2oracle: fix creating edges in imported objects

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/level-filter.exp.json
=> globs: level filter

d2compiler/compile_test.go, testdata/d2compiler/TestCompile2/globs/and-filter.exp.json
=> add test for and ampersand

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/level-filter.exp.json
=> d2ir: filter edge by src/dst non-field properties

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/import.go, testdata/d2compiler/TestCompile/import-nested-var.exp.json
=> d2ir: attempt resolving substitutions from imported files at imported scope first

ci/release/changelogs/next.md, d2plugin/plugin.go
closes https://github.com/terrastruct/d2/issues/2414
=> plugin: ignore name casing

ci/release/changelogs/next.md, d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile/composite-glob-filter.exp.json
=> d2ir: fix error handling for composite glob filter

d2compiler/compile.go, d2oracle/edit_test.go, d2oracle/get.go, testdata/d2oracle/TestSet/set-style-in-layer.exp.json
=> d2oracle: fix setting in multiple layers

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestUpdateImport/in_layer.exp.json, testdata/d2oracle/TestUpdateImport/layer_import.exp.json, testdata/d2oracle/TestUpdateImport/mixed_imports.exp.json, testdata/d2oracle/TestUpdateImport/multiple_imports.exp.json, testdata/d2oracle/TestUpdateImport/nested_import.exp.json, testdata/d2oracle/TestUpdateImport/no_matching_import.exp.json, testdata/d2oracle/TestUpdateImport/remove_import.exp.json, testdata/d2oracle/TestUpdateImport/remove_nested_import.exp.json, testdata/d2oracle/TestUpdateImport/remove_spread_import.exp.json, testdata/d2oracle/TestUpdateImport/update_import.exp.json, testdata/d2oracle/TestUpdateImport/update_import_with_dir.exp.json, testdata/d2oracle/TestUpdateImport/update_spread_import.exp.json
=> d2oracle: UpdateImport

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestUpdateImport/remove_directory_import.exp.json, testdata/d2oracle/TestUpdateImport/update_deep_directory_paths.exp.json, testdata/d2oracle/TestUpdateImport/update_directory_import.exp.json
=> d2oracle.UpdateImport: support directory updates

d2oracle/edit.go, d2oracle/edit_test.go
=> d2oracle: update signature of UpdateImport

d2oracle/edit.go, d2oracle/edit_test.go
=> handle relative paths for updating imports

ci/release/release.sh
=> revert release script changes

d2compiler/compile_test.go, d2ir/compile.go, testdata/d2compiler/TestCompile2/globs/glob-edge-filter.exp.json
fixes https://github.com/terrastruct/d2/issues/2363#issuecomment-2850055521
=> Fix edge filter

d2renderers/d2svg/d2svg.go
=> expose renderLegend as a public API

lib/jsrunner/js.go
https://github.com/terrastruct/d2/pull/2504/
credit to @chai2010
=> fix(lib/jsrunner): use the key parameter in MustGet instead of hardcoded "elkResult"

README.md
Two more community tools:
* MessageFlow - generate diagrams from AsyncAPI specifications. Example: https://github.com/holydocs/messageflow/tree/main/examples/docs
* DBerd - generate entity relation diagram of multiple databases: PostgreSQL, MySQL, CockroachDB, ClickHouse, MongoDB
=> readme: messageflow+dberd

ci/release/_install.sh, install.sh
seeing some ci runs periodically fail as well
closes https://github.com/terrastruct/d2/issues/2542
=> install.sh: automatic retries

d2plugin/serve.go
closes https://github.com/terrastruct/TALA/issues/98
=> fix plugin --help

ci/release/_install.sh, install.sh
https://github.com/terrastruct/d2/issues/2583
=> consistent version format

d2cli/main.go
=> ascii cli: only change to elk if layout is dagre

d2js/d2wasm/functions.go, d2js/js/ci/build.sh, d2js/js/src/worker.js
=> update wasm flag

.github/workflows/daily.yml, ci/peek-wasm-size.sh, ci/release/build_in_docker.sh, d2cli/play.go, d2js/js/README.md, d2js/js/ci/build.sh, go.mod
=> update to go 1.24

d2js/js/package.json, d2js/js/src/index.js, d2js/js/src/worker.browser.js, d2js/js/src/worker.js, d2js/js/src/worker.node.js, d2js/js/test/unit/basic.test.js, d2js/js/test/unit/encoding.test.js
=> d2js: encoding

d2js/d2wasm/functions.go, d2js/js.go, d2js/js/ci/build.sh, d2js/js/src/index.js, d2js/js/src/worker.browser.js, d2js/js/src/worker.js, d2js/js/src/worker.node.js, d2js/js/test/unit/basic.test.js
=> add jsversion

d2oracle/edit.go, d2oracle/edit_test.go, testdata/d2oracle/TestCreate/add_layer/6.exp.json
=> d2oracle: error for board adding

ci/release/changelogs/next.md, lib/pptx/pptx.go, lib/pptx/templates/core.xml, lib/pptx/templates/presentation.xml, lib/pptx/templates/root_rels.xml, lib/pptx/templates/slide.xml, lib/pptx/templates/slidemaster_rels.xml, lib/pptx/validate.go
=> fix malformed pptx outputs

lib/pptx/pptx.go, lib/pptx/validate.go
followup https://github.com/terrastruct/d2/pull/2645
=> fix pptx again

README.md
=> update d2studio backlink

ci/release/changelogs/next.md, ci/release/docker/Dockerfile, ci/release/template/man/d2.1, d2cli/main.go, go.mod, go.sum, lib/png/png.go
closes https://github.com/terrastruct/d2/issues/2502
=> Playwright stuff
